/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import oru.inf.InfDB;
import oru.inf.InfException;
import javax.swing.JOptionPane;
/**
 *
 * @author lucya
 */
public class Administratör extends javax.swing.JFrame {
    
    private InfDB idb;
    private String ePost;
    
private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MenyAdministrator.class.getName());

    public Administratör(InfDB idb, String ePost) { // Denna rad är viktig!
        this.idb = idb;
        this.ePost = ePost;
        initComponents();
    }
    
    private void laggTillAvdelning() {
    try {
        String namn = btnAvdId.getText();
        String beskrivning = btnPartner.getText();
        String nyttId = idb.getAutoIncrement("avdelning", "avdid");

        String fraga = "INSERT INTO avdelning (avdid, namn, beskrivning) VALUES (" + nyttId + ", '" + namn + "', '" + beskrivning + "')";
        
        idb.insert(fraga);
        javax.swing.JOptionPane.showMessageDialog(null, "Avdelningen har sparats!");
    } // Denna stänger try
    catch (Exception ettFel) {
        javax.swing.JOptionPane.showMessageDialog(null, "Något gick fel!");
    } // Denna stänger catch
} // Denna stänger hela metoden laggTillAvdelning
    
private void andraAvdelning() {
    try {
        String nyttNamn = btnAvdId.getText();
        String nyBeskrivning = btnPartner.getText();
        
        // Du måste definiera 'id' här! Exempelvis från ett textfält:
        String id = btnAvdId.getText(); 

        String fraga = "UPDATE avdelning SET namn = '" + nyttNamn + "', beskrivning = '" + nyBeskrivning + "' WHERE avdid = " + id;
        
        idb.update(fraga);
        JOptionPane.showMessageDialog(null, "Avdelningen har uppdaterats!");
    } 
    catch (Exception ettFel) {
        JOptionPane.showMessageDialog(null, "Kunde inte uppdatera!");
    }
}
   
    
        
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnLand = new javax.swing.JButton();
        btnAvdId = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnPartner = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnLand.setText("Land");
        btnLand.addActionListener(this::btnLandActionPerformed);

        btnAvdId.setText("Avdelning");
        btnAvdId.addActionListener(this::btnAvdIdActionPerformed);

        jLabel1.setText("Redigera uppgifter");

        btnPartner.setText("Partner");
        btnPartner.addActionListener(this::btnPartnerActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 158, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnLand, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnPartner, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnAvdId, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(141, 141, 141))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAvdId)
                .addGap(18, 18, 18)
                .addComponent(btnPartner)
                .addGap(18, 18, 18)
                .addComponent(btnLand)
                .addContainerGap(117, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLandActionPerformed
        new AdminLandUppgifter(idb).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLandActionPerformed

    private void btnAvdIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAvdIdActionPerformed
        // TODO add your handling code here:
        new AdminAvdelningUppgifter(idb).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAvdIdActionPerformed

    private void btnPartnerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPartnerActionPerformed
        // TODO add your handling code here:
        new AdminPartnerUppgifter(idb).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnPartnerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            //logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        //java.awt.EventQueue.invokeLater(() -> new Administratör(null).setVisible(true));
    }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAvdId;
    private javax.swing.JButton btnLand;
    private javax.swing.JButton btnPartner;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}

