/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import oru.inf.InfDB; 
import javax.swing.JOptionPane;
/**
 *
 * @author lucya
 */
public class AdminPartnerUppgifter extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AdminPartnerUppgifter.class.getName());
    private InfDB idb;
    /**
     * Creates new form AdminPartnerUppgifter
     */
    public AdminPartnerUppgifter(InfDB idb) {
        this.idb = idb;
        initComponents();
        txtId.setVisible(false);
jLabel2.setVisible(false); // Detta döljer även texten "ID"
fyllPartnerLista();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        txtNamn = new javax.swing.JTextField();
        txtKontaktperson = new javax.swing.JTextField();
        txtEpost = new javax.swing.JTextField();
        txtTelefon = new javax.swing.JTextField();
        txtAdress = new javax.swing.JTextField();
        txtBransch = new javax.swing.JTextField();
        txtStad = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnTillbaka = new javax.swing.JButton();
        cmbPartners = new javax.swing.JComboBox<>();
        btnSparaPartner = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Redigera Partner uppgifter");

        txtId.addActionListener(this::txtIdActionPerformed);

        jLabel2.setText("ID");

        jLabel3.setText("Namn");

        jLabel4.setText("Kontaktperson");

        jLabel5.setText("Epost");

        jLabel6.setText("Telefon");

        jLabel7.setText("Adress");

        jLabel8.setText("Bransch");

        jLabel9.setText("Stad");

        btnTillbaka.setText("Tillbaka");
        btnTillbaka.addActionListener(this::btnTillbakaActionPerformed);

        cmbPartners.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbPartners.addActionListener(this::cmbPartnersActionPerformed);

        btnSparaPartner.setText("Spara");
        btnSparaPartner.addActionListener(this::btnSparaPartnerActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(124, 124, 124)
                                .addComponent(jLabel1))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addComponent(cmbPartners, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 111, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnSparaPartner))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtNamn, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(txtKontaktperson, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(txtEpost, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(txtId)
                                            .addComponent(txtTelefon)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtAdress))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtBransch))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtStad)))))))
                .addGap(50, 50, 50))
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(btnTillbaka)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(cmbPartners, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtKontaktperson, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEpost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTelefon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAdress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBransch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtStad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addComponent(btnSparaPartner)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(btnTillbaka)
                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdActionPerformed

    private void btnTillbakaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTillbakaActionPerformed
        // TODO add your handling code here:
                                                                                             
    // Stänger ner det nuvarande fönstret
    this.dispose();
    
    // Öppnar klassen Administrator istället
    new Administratör(idb, "Admin").setVisible(true);

    }//GEN-LAST:event_btnTillbakaActionPerformed

    private void cmbPartnersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbPartnersActionPerformed
        // TODO add your handling code here:
        try {
    // Hämta namnet som användaren just klickade på
    String valtNamn = cmbPartners.getSelectedItem().toString();
    
    // Fråga databasen efter ALL info om just den partnern
    String fraga = "SELECT * FROM partner WHERE namn = '" + valtNamn + "'";
    java.util.HashMap<String, String> rad = idb.fetchRow(fraga);

    if (rad != null) {
        // Fyll i de dolda och synliga fälten med info från databasen
        txtId.setText(rad.get("pid"));
        txtNamn.setText(rad.get("namn"));
        txtKontaktperson.setText(rad.get("kontaktperson"));
        txtEpost.setText(rad.get("kontaktepost"));
        txtTelefon.setText(rad.get("telefon"));
        txtAdress.setText(rad.get("adress"));
        txtBransch.setText(rad.get("branch"));
        txtStad.setText(rad.get("stad"));
    }
} catch (Exception e) {
    // Tom catch för att undvika felmeddelanden när listan rensas/uppdateras
}
    }//GEN-LAST:event_cmbPartnersActionPerformed

    private void btnSparaPartnerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSparaPartnerActionPerformed
        // TODO add your handling code here:
                                                   
    try {
        // Vi hämtar ID från det dolda fältet för att veta vilken partner vi ska ändra
        String id = txtId.getText();
        
        if (id.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Välj en partner i listan först.");
            return;
        }

        // Här skapar vi SQL-frågan. 
        // OBS: Dubbelkolla om kolumnen heter 'branch' eller 'bransch' i din databas!
        String fraga = "UPDATE partner SET "
                + "namn = '" + txtNamn.getText() + "', "
                + "kontaktperson = '" + txtKontaktperson.getText() + "', "
                + "kontaktepost = '" + txtEpost.getText() + "', "
                + "telefon = '" + txtTelefon.getText() + "', "
                + "adress = '" + txtAdress.getText() + "', "
                + "branch = '" + txtBransch.getText() + "', " // Ändra till 'bransch' om det behövs
                + "stad = '" + txtStad.getText() + "' "
                + "WHERE pid = " + id;

        idb.update(fraga);
        JOptionPane.showMessageDialog(this, "Partnerns uppgifter har sparats!");
        
        // Uppdatera rullistan ifall namnet har ändrats
        fyllPartnerLista();
        
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Fel vid lagring: " + e.getMessage());
    }

    }//GEN-LAST:event_btnSparaPartnerActionPerformed

    /**
     * @param args the command line arguments
     */
    //public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
      //  try {
        //    for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
          //      if ("Nimbus".equals(info.getName())) {
            //        javax.swing.UIManager.setLookAndFeel(info.getClassName());
              //      break;
                //}
            //}
        //} catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
          //  logger.log(java.util.logging.Level.SEVERE, null, ex);
        //}
        //</editor-fold>

        /* Create and display the form */
        //java.awt.EventQueue.invokeLater(() -> new AdminPartnerUppgifter().setVisible(true));
    //}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSparaPartner;
    private javax.swing.JButton btnTillbaka;
    private javax.swing.JComboBox<String> cmbPartners;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtAdress;
    private javax.swing.JTextField txtBransch;
    private javax.swing.JTextField txtEpost;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtKontaktperson;
    private javax.swing.JTextField txtNamn;
    private javax.swing.JTextField txtStad;
    private javax.swing.JTextField txtTelefon;
    // End of variables declaration//GEN-END:variables
private void fyllPartnerLista() {
    try {
        // Ta bort "Item 1, Item 2" som NetBeans lägger dit som standard
        cmbPartners.removeAllItems(); 
        
        // Hämta alla namn från kolumnen 'namn' i tabellen 'partner'
        String fraga = "SELECT namn FROM partner";
        java.util.ArrayList<String> allaPartner = idb.fetchColumn(fraga);

        // Om vi fick svar från databasen, lägg till varje namn i rullistan
        if (allaPartner != null) {
            for (String namn : allaPartner) {
                cmbPartners.addItem(namn);
            }
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Kunde inte ladda partners: " + e.getMessage());
    }
}

    private void rensaFalt() {
    txtId.setText("");
    txtNamn.setText("");
    txtKontaktperson.setText("");
    txtEpost.setText("");
    txtTelefon.setText("");
    txtAdress.setText("");
    txtBransch.setText("");
    txtStad.setText("");
}
}



