/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import oru.inf.InfDB;
import oru.inf.InfException;
import javax.swing.JOptionPane;
/**
 *
 * @author lucya
 */
public class Administratör extends javax.swing.JFrame {
    
    // Variabler för att hålla databaskopplingen och inloggad användare
    private InfDB idb;
    private String ePost;
    
private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MenyAdministrator.class.getName());

// Konstruktor: Körs när fönstret skapas
    public Administratör(InfDB idb, String ePost) { 
        this.idb = idb;
        this.ePost = ePost;
        initComponents(); // Skapar alla knappar och rutor från design-vyn
    }
    
    

   
    
        
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnLand = new javax.swing.JButton();
        btnAvdId = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnPartner = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnLand.setText("Land");
        btnLand.addActionListener(this::btnLandActionPerformed);

        btnAvdId.setText("Avdelning");
        btnAvdId.addActionListener(this::btnAvdIdActionPerformed);

        jLabel1.setText("Redigera uppgifter");

        btnPartner.setText("Partner");
        btnPartner.addActionListener(this::btnPartnerActionPerformed);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Välkommen Administratör");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(btnAvdId, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPartner, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLand, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(96, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(83, 83, 83))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAvdId)
                .addGap(18, 18, 18)
                .addComponent(btnPartner)
                .addGap(18, 18, 18)
                .addComponent(btnLand)
                .addContainerGap(83, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLandActionPerformed
        // Öppnar fönstret för landhantering och stänger huvudmenyn
        new AdminLandUppgifter(idb).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLandActionPerformed

    private void btnAvdIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAvdIdActionPerformed
        // TODO add your handling code here:
        // Öppnar fönstret för avdelningshantering
        new AdminAvdelningUppgifter(idb).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAvdIdActionPerformed

    private void btnPartnerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPartnerActionPerformed
        // TODO add your handling code here:
       // Öppnar fönstret för partnerhantering
        new AdminPartnerUppgifter(idb).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnPartnerActionPerformed

    /**
     * @param args the command line arguments
     */
    // Main-metoden som startar fönstret
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            //logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        //java.awt.EventQueue.invokeLater(() -> new Administratör(null).setVisible(true));
    }


// Här deklareras alla knappar och rubriker som skapats i Design-vyn
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAvdId;
    private javax.swing.JButton btnLand;
    private javax.swing.JButton btnPartner;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}

