/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import oru.inf.InfDB;
import oru.inf.InfException;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author oliviacollin
 */
public class HandlaggareAvdProjekt extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(HandlaggareAvdProjekt.class.getName());
    private InfDB idb;
    private String inloggadAnvandare;

    /**
     * Creates new form HandlaggareAvdProjekt
     */
    public HandlaggareAvdProjekt(InfDB idb, String inloggadAnvandare) {
        this.idb = idb;
        this.inloggadAnvandare = inloggadAnvandare;
        initComponents();
    }

    private void uppdateraProjektLista() {
        try {
            // 1. Kontrollera inloggad användare
            if (inloggadAnvandare == null || inloggadAnvandare.isEmpty()) {
                return;
            }

            // 2. Hämta avdelnings-ID för den inloggade
            String avdFraga = "SELECT avdelning FROM anstalld WHERE epost = '" + inloggadAnvandare + "'";
            String avdelningId = idb.fetchSingle(avdFraga);

            if (avdelningId == null) {
                jTextArea1.setText("Kunde inte hitta din avdelning.");
                return;
            }

            // 3. Hämta alla anställda (aid) på den avdelningen
            String anstalldaFraga = "SELECT aid FROM anstalld WHERE avdelning = '" + avdelningId + "'";
            ArrayList<String> allaAid = idb.fetchColumn(anstalldaFraga);

            if (allaAid == null || allaAid.isEmpty()) {
                jTextArea1.setText("Inga anställda hittades på din avdelning.");
                return;
            }

            // 4. Formatera ID-listan med fnuttar: ('3','31','32'...)
            ArrayList<String> formateradeAid = new ArrayList<>();
            for (String aid : allaAid) {
                if (aid != null) {
                    formateradeAid.add("'" + aid.trim() + "'");
                }
            }
            String aidLista = String.join(",", formateradeAid);

            // 5. Hämta vald status och hantera Å-problemet
            if (cbStatus.getSelectedItem() == null) {
                return;
            }
            String valdStatus = cbStatus.getSelectedItem().toString();
            if (valdStatus.equals("Välj status")) {
                jTextArea1.setText("");
                return;
            }

            String statusFilter = valdStatus;
            if (valdStatus.equalsIgnoreCase("Pågående")) {
                statusFilter = "P%g%ende";
            }

            // 6. Slutgiltig SQL - Nu med 'projektchef'
            String fraga = "SELECT projektnamn FROM projekt "
                    + "WHERE status LIKE '" + statusFilter + "' "
                    + "AND projektchef IN (" + aidLista + ")";

            System.out.println("DEBUG - Kör SQL: " + fraga);
            ArrayList<String> projekt = idb.fetchColumn(fraga);

            // 7. Visa resultatet
            jTextArea1.setText("");
            if (projekt != null && !projekt.isEmpty()) {
                for (String namn : projekt) {
                    jTextArea1.append(namn + "\n");
                }
            } else {
                jTextArea1.setText("Inga projekt hittades för " + valdStatus + " på din avdelning.");
            }

        } catch (Exception e) {
            System.out.println("FEL: " + e.getMessage());
            JOptionPane.showMessageDialog(this, "Ett fel uppstod: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblrojekt = new javax.swing.JLabel();
        cbStatus = new javax.swing.JComboBox<>();
        scpText = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        btnTillbaka = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblrojekt.setText("Projekt på min avdelning");

        cbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Välj status", "Pågående", "Planerat", "Avslutat" }));
        cbStatus.addActionListener(this::cbStatusActionPerformed);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        scpText.setViewportView(jTextArea1);

        btnTillbaka.setText("Tillbaka till menyn");
        btnTillbaka.addActionListener(this::btnTillbakaActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnTillbaka)
                    .addComponent(scpText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblrojekt))
                .addContainerGap(139, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lblrojekt)
                .addGap(18, 18, 18)
                .addComponent(cbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scpText, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnTillbaka)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbStatusActionPerformed
        uppdateraProjektLista();

    }//GEN-LAST:event_cbStatusActionPerformed

    private void btnTillbakaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTillbakaActionPerformed
        // TODO add your handling code here:
        new MenyHandläggare(idb, inloggadAnvandare).setVisible(true);
        this.dispose(); // Stänger ner detta fönster
    }//GEN-LAST:event_btnTillbakaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTillbaka;
    private javax.swing.JComboBox<String> cbStatus;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lblrojekt;
    private javax.swing.JScrollPane scpText;
    // End of variables declaration//GEN-END:variables
}
