/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import oru.inf.InfDB;
import oru.inf.InfException;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.JOptionPane;
/**
 *
 * @author oliviacollin
 */
/**
 * Klass för att visa samarbetspartners för de projekt som handläggaren deltar i.
 */
public class HandlaggarePartner extends javax.swing.JFrame {
    private InfDB idb;
    private String inloggadAnvandare;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(HandlaggarePartner.class.getName());

    /**
     * Creates new form HandlaggarePartner
     */
    public HandlaggarePartner(InfDB idb, String inloggadAnvandare) {
        this.idb = idb;
        this.inloggadAnvandare = inloggadAnvandare;
        initComponents();
        hamtaMinaPartners();
    }
    // METOD: Hämtar partners genom att koppla ihop fyra olika tabeller
private void hamtaMinaPartners() {
    try {
        // Uppdaterad SQL-fråga baserat på ditt skript:
        // Partner-ID i 'partner' heter pid.
        // Partner-ID i 'projekt_partner' heter partner_pid.
        // Projekt-ID i 'projekt_partner' heter pid.
        String fraga = "SELECT partner.namn, partner.kontaktepost, partner.telefon FROM partner " +
                       "JOIN projekt_partner ON partner.pid = projekt_partner.partner_pid " +
                       "JOIN ans_proj ON projekt_partner.pid = ans_proj.pid " +
                       "JOIN anstalld ON ans_proj.aid = anstalld.aid " +
                       "WHERE anstalld.epost = '" + inloggadAnvandare + "'";

        // Debug: Skriver ut frågan i Output så du kan kontrollera den
        System.out.println("Kör SQL: " + fraga);

        ArrayList<HashMap<String, String>> resultat = idb.fetchRows(fraga);
// Skapar en StringBuilder för att snyggt bygga upp texten som ska visas
        StringBuilder sb = new StringBuilder();
        sb.append("Partnernamn\t\tE-post\n");
        sb.append("------------------------------------------------------------\n");
// Kontrollerar om vi fick några träffar
        if (resultat != null && !resultat.isEmpty()) {
            for (HashMap<String, String> rad : resultat) {
                // Hämta värdena med exakt samma namn som i SELECT-frågan
                String namn = rad.get("namn");
                String epost = rad.get("kontaktepost");
                
                sb.append(namn).append("\t\t").append(epost).append("\n");
            }
            txtPartners.setText(sb.toString());
        } else {
            txtPartners.setText("Inga samarbetspartners hittades för dina projekt.");
        }
    } catch (Exception e) {
        // Detta visar det felmeddelande du såg på bilden
        JOptionPane.showMessageDialog(this, "Fel vid hämtning av partners: " + e.getMessage());
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtPartners = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Mina samarbetspartners");

        jButton1.setText("Tillbaka");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        txtPartners.setColumns(20);
        txtPartners.setRows(5);
        jScrollPane1.setViewportView(txtPartners);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(54, 54, 54))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
//kommer tillbaka till meny
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
    new MenyHandläggare(idb, inloggadAnvandare).setVisible(true);
    this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
   // public static void main(String args[]) {
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtPartners;
    // End of variables declaration//GEN-END:variables
}
