/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import oru.inf.InfException;
import oru.inf.InfDB;
import java.util.HashMap;
import javax.swing.JOptionPane;     
/**
 *
 * @author User
 */
public class handlaggarUppgifter extends javax.swing.JFrame {
    private InfDB idb;
    private String inloggadAnvandare;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(handlaggarUppgifter.class.getName());

    /**
     * Creates new form handlaggarUppgifter
     */
    public handlaggarUppgifter(InfDB idb, String inloggadAnvandare) {
        this.idb = idb;
        this.inloggadAnvandare = inloggadAnvandare;
        initComponents();
        fyllProfilFalt();
    }
                                       

    public void fyllProfilFalt() {
        try {
            String fraga = "SELECT * FROM anstalld WHERE epost ='" + inloggadAnvandare + "'";
            HashMap<String, String> rad = idb.fetchRow(fraga);
            
            if (rad != null) {
                txtAdress.setText(rad.get("adress"));
                txtEpost.setText(rad.get("epost"));
                txtTelefon.setText(rad.get("telefon"));
                txtLosenord.setText(rad.get("losenord"));
                
                if (lblNamn != null) {
                    lblNamn.setText(rad.get("fornamn") + " " + rad.get("efternamn"));
                }
            }
        } catch (InfException ex) {
            JOptionPane.showMessageDialog(null, "Databasfel: " + ex.getMessage());
        }
    }
                                                 
   
    private javax.swing.JLabel lblNamn;


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtAdress = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtEpost = new javax.swing.JTextField();
        txtTelefon = new javax.swing.JTextField();
        txtLosenord = new javax.swing.JPasswordField();
        btnSpara = new javax.swing.JButton();
        tillbakaKnapp = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Dina uppgifter: ");

        jLabel2.setText("Adress:");

        txtAdress.setText("jTextField1");

        jLabel3.setText("Epost: ");

        jLabel4.setText("Telefonnummer");

        jLabel5.setText("Lösenord: ");

        txtEpost.setText("jTextField2");

        txtTelefon.setText("jTextField3");

        txtLosenord.setText("jPasswordField1");

        btnSpara.setText("Spara ändringar");
        btnSpara.addActionListener(this::btnSparaActionPerformed);

        tillbakaKnapp.setText("Tillbaka");
        tillbakaKnapp.addActionListener(this::tillbakaKnappActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSpara)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtTelefon)
                                .addComponent(txtLosenord, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                                .addComponent(txtEpost)
                                .addComponent(txtAdress))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(tillbakaKnapp)))
                .addContainerGap(253, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAdress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtEpost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtTelefon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtLosenord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(btnSpara)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 131, Short.MAX_VALUE)
                .addComponent(tillbakaKnapp)
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSparaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSparaActionPerformed
  
        if (Valideringsklass2.faltHarVarde(txtAdress,) && 
            Valideringsklass2.faltHarVarde(txtTelefon) && 
            Valideringsklass2.arGiltigtTelefonnummer(txtTelefon) &&
            Valideringsklass2.faltHarVarde(txtLosenord)) {
            
            try {
             
                String nyAdress = txtAdress.getText().trim();
                String nyTel = txtTelefon.getText().trim();
                String nyttLosen = new String(txtLosenord.getPassword());

                
                String updateFraga = "UPDATE anstalld SET "
                        + "adress = '" + nyAdress + "', "
                        + "telefon = '" + nyTel + "', "
                        + "losenord = '" + nyttLosen + "' "
                        + "WHERE epost = '" + inloggadAnvandare + "'";
                
               
                idb.update(updateFraga);
                JOptionPane.showMessageDialog(null, "Dina uppgifter har uppdaterats!");

            } catch (InfException ex) {
                JOptionPane.showMessageDialog(null, "Kunde inte spara: " + ex.getMessage());    
            }  
        
    } 
    }//GEN-LAST:event_btnSparaActionPerformed

    private void tillbakaKnappActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tillbakaKnappActionPerformed
      new MenyHandläggare(idb, inloggadAnvandare).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_tillbakaKnappActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSpara;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton tillbakaKnapp;
    private javax.swing.JTextField txtAdress;
    private javax.swing.JTextField txtEpost;
    private javax.swing.JPasswordField txtLosenord;
    private javax.swing.JTextField txtTelefon;
    // End of variables declaration//GEN-END:variables
  }
