/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import oru.inf.InfDB;
import oru.inf.InfException;
/**
 *
 * @author oliviacollin
 */
public class Handläggareprojekt extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Handläggareprojekt.class.getName());
    private InfDB idb;
    private String inloggadAnvandare;
    /**
     * Creates new form Handläggareprojekt
     */
    public Handläggareprojekt(InfDB idb, String inloggadAnvandare) {
        this.idb = idb;
        this.inloggadAnvandare = inloggadAnvandare;
        initComponents();
        hamtaMinaProjekt();
    

 

    }
  private void hamtaMinaProjekt() {
    try {
        // Vi hämtar projektnamn, status och kostnad för de projekt där användaren är chef
        // Vi använder en sub-query för att hitta rätt AID via e-posten
        String fraga = "SELECT projektnamn, status, kostnad FROM projekt " +
                       "WHERE projektchef = (SELECT aid FROM anstalld WHERE epost = '" + inloggadAnvandare + "')";

        // fetchRows hämtar FLERA rader (en lista med HashMaps)
        java.util.ArrayList<java.util.HashMap<String, String>> projektLista = idb.fetchRows(fraga);

        if (projektLista != null) {
            StringBuilder sb = new StringBuilder();
            sb.append("Mina ledda projekt:\n");
            sb.append("------------------------------------------\n");

            for (java.util.HashMap<String, String> rad : projektLista) {
                sb.append("Namn: ").append(rad.get("projektnamn")).append("\n");
                sb.append("Status: ").append(rad.get("status")).append("\n");
                sb.append("Budget: ").append(rad.get("kostnad")).append(" kr\n");
                sb.append("------------------------------------------\n");
            }
            txtMinaProjekt.setText(sb.toString());
        } else {
            txtMinaProjekt.setText("Du står inte som chef för några projekt just nu.");
        }
    } catch (InfException ex) {
        javax.swing.JOptionPane.showMessageDialog(null, "Fel vid hämtning av projekt: " + ex.getMessage());
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtMinaProjekt = new javax.swing.JTextArea();
        btnTillbaka = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtMinaProjekt.setEditable(false);
        txtMinaProjekt.setColumns(20);
        txtMinaProjekt.setRows(5);
        jScrollPane1.setViewportView(txtMinaProjekt);

        btnTillbaka.setText("jButton1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(btnTillbaka))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(142, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(btnTillbaka)
                .addGap(46, 46, 46))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        //(ava.awt.EventQueue.invokeLater(() -> new Handläggareprojekt(null).setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTillbaka;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtMinaProjekt;
    // End of variables declaration//GEN-END:variables
}
