/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import oru.inf.InfDB;
import oru.inf.InfException;

public class HandläggarePersonal extends javax.swing.JFrame {

    private InfDB idb;
    private String inloggadAnvandare;

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(HandläggarePersonal.class.getName());

    /**
     * Öppnar en lista med personal på min avdelning direkt i konstruktorn.
     */
    public HandläggarePersonal(InfDB idb, String inloggadAnvandare) {
        this.idb = idb;
        this.inloggadAnvandare = inloggadAnvandare;
        initComponents();
        listaPersonalPaMinAvd();
    }

    /**
     * Metoden som skapar listan, anropas sedan i konstruktorn ovan.
     */
    public void listaPersonalPaMinAvd() {
        try {
            String avdId = idb.fetchSingle("SELECT avdelning FROM anstalld WHERE epost = '" + inloggadAnvandare + "'");
            if (avdId != null) {
                String fraga = "SELECT CONCAT(fornamn , ' ' , efternamn) FROM anstalld WHERE avdelning = " + "'" + avdId + "'";
                java.util.ArrayList<String> namnLista = idb.fetchColumn(fraga);

                if (namnLista != null) {
                    javax.swing.DefaultListModel<String> lista = new javax.swing.DefaultListModel<>();

                    for (String namn : namnLista) {
                        lista.addElement(namn);

                    }
                    personalLista.setModel(lista);
                }
            }

        } catch (InfException felMeddelande) {
            System.out.println("Det har uppstått ett fel!" + felMeddelande.getMessage());

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        personalLista = new javax.swing.JList<>();
        tillbakaTillMeny = new javax.swing.JButton();
        titel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setViewportView(personalLista);

        tillbakaTillMeny.setText("Tillbaka");
        tillbakaTillMeny.addActionListener(this::tillbakaTillMenyActionPerformed);

        titel.setText("Personal på din avdelning:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tillbakaTillMeny)
                            .addComponent(titel))
                        .addGap(0, 419, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titel)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(tillbakaTillMeny)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tillbakaTillMenyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tillbakaTillMenyActionPerformed
        new MenyHandläggare(idb, inloggadAnvandare).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_tillbakaTillMenyActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> personalLista;
    private javax.swing.JButton tillbakaTillMeny;
    private javax.swing.JLabel titel;
    // End of variables declaration//GEN-END:variables
}
