/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 * Klassen ansvarar för att hantera kopplingen mellan projekt och partners
 * Projektchefen kan se sina egna projekt  och koppla/ta bort partners
 * @author elinjugas
 */
import oru.inf.InfDB;
import oru.inf.InfException;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

public class HanteraProjektPartners extends javax.swing.JFrame {

    private InfDB idb;
    private String inloggadAnvandare; //Lagrar epost

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(HanteraProjektPartners.class.getName());

    /**
     * Creates new form HanteraProjektPartners
     */
    public HanteraProjektPartners(InfDB idb, String inloggadAnvandare) {
        initComponents();
        this.idb = idb;
        this.inloggadAnvandare = inloggadAnvandare;
//Fyller listor direkt vid start för att ge användaren överblick över projekt och partners
        fyllMinaProjekt();
        fyllAllaPartners();
    }

    private void fyllMinaProjekt() {
        // Hämtar projekt från databasen där användaren är projektchef.
        //Så att chefen bara kan ändra i sina egna projekt
       try {
        DefaultListModel<String> model = new DefaultListModel<>();
        
        // Join för att filtrera projekt baserat på inloggade e-post
        String fraga = "SELECT projektnamn FROM projekt "
                + "JOIN anstalld ON projekt.projektchef = anstalld.aid "
                + "WHERE anstalld.epost = '" + inloggadAnvandare + "'";

        ArrayList<String> projekt = idb.fetchColumn(fraga);
        if (projekt != null) {
            for (String p : projekt) {
                model.addElement(p);
            }
        }
        lstMinaProjekt.setModel(model);
    } catch (InfException ex) {
        // Felmeddelande vid databasproblem
        JOptionPane.showMessageDialog(this, "Kunde inte hämta dina projekt. Kontrollera databasanslutningen.");
    }
    }

    /**
     * Hämtar alla tillgängliga partners för att kunna erbjuda dem som alternativ i gränssnittet.
     */
    private void fyllAllaPartners() {
        try {
            DefaultListModel<String> model = new DefaultListModel<>();
            ArrayList<String> partners = idb.fetchColumn("SELECT namn FROM partner");
            if (partners != null) {
                for (String p : partners) {
                    model.addElement(p);
                }
            }
            lstAllaPartners.setModel(model);
        } catch (InfException ex) {
            System.out.println("Fel vid hämtning av partners: " + ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pnlMain = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstMinaProjekt = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstAllaPartners = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnKoppla = new javax.swing.JButton();
        btnTaBort = new javax.swing.JButton();
        btnTillbaka = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 153, 255));
        setPreferredSize(new java.awt.Dimension(700, 500));

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 64, Short.MAX_VALUE)
        );

        lstMinaProjekt.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(lstMinaProjekt);

        lstAllaPartners.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(lstAllaPartners);

        jLabel1.setText("Mina projekt:");

        jLabel2.setText("Partners:");

        btnKoppla.setText("Lägg till:");
        btnKoppla.addActionListener(this::btnKopplaActionPerformed);

        btnTaBort.setText("Ta bort:");
        btnTaBort.addActionListener(this::btnTaBortActionPerformed);

        javax.swing.GroupLayout pnlMainLayout = new javax.swing.GroupLayout(pnlMain);
        pnlMain.setLayout(pnlMainLayout);
        pnlMainLayout.setHorizontalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMainLayout.createSequentialGroup()
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMainLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jLabel1))
                    .addGroup(pnlMainLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66)
                        .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnKoppla)
                            .addComponent(btnTaBort))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );
        pnlMainLayout.setVerticalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMainLayout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMainLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlMainLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(btnKoppla)
                        .addGap(18, 18, 18)
                        .addComponent(btnTaBort)))
                .addGap(16, 16, 16))
        );

        btnTillbaka.setText("Tillbaka");
        btnTillbaka.addActionListener(this::btnTillbakaActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnTillbaka)
                    .addComponent(pnlMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnTillbaka)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnKopplaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKopplaActionPerformed
    //  Validera att användaren valt något i listorna
    if (Valideringsklass2.listidArValt(lstMinaProjekt.getSelectedValue(), "projekt") &&
        Valideringsklass2.listidArValt(lstAllaPartners.getSelectedValue(), "partner")) {
        
        try {
            String valtProjekt = lstMinaProjekt.getSelectedValue();
            String valdPartner = lstAllaPartners.getSelectedValue();

            // Hämta ID:n
            String pId = idb.fetchSingle("SELECT pid FROM projekt WHERE projektnamn = '" + valtProjekt + "'");
            String partnerId = idb.fetchSingle("SELECT pid FROM partner WHERE namn = '" + valdPartner + "'");

            // Säkerhetskontroll som validerar ID
            if (Valideringsklass2.arGiltigtId(pId) && Valideringsklass2.arGiltigtId(partnerId)) {
                idb.insert("INSERT INTO projekt_partner (pid, partner_pid) VALUES (" + pId + ", " + partnerId + ")");
                JOptionPane.showMessageDialog(this, valdPartner + " har lagts till i " + valtProjekt);
            }

        } catch (InfException ex) {
            //För att säkerhetställa så inga dubletter sker vid koppling
            if (ex.getMessage().contains("Duplicate")) {
                JOptionPane.showMessageDialog(this, "Partnern är redan kopplad till detta projekt.");
            } else {
                JOptionPane.showMessageDialog(this, "Ett tekniskt fel uppstod: " + ex.getMessage());
            }
        }  
    }

    }//GEN-LAST:event_btnKopplaActionPerformed

    private void btnTillbakaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTillbakaActionPerformed
        new ProjektchefPartneradministration(idb, inloggadAnvandare).setVisible(true);
        this.dispose();

    }//GEN-LAST:event_btnTillbakaActionPerformed

    // För att ta bort en koppling mellan projekt och partners
    private void btnTaBortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaBortActionPerformed
       // Validerar att användaren faktiskt valt något i båda listorna
        if (Valideringsklass2.listidArValt(lstMinaProjekt.getSelectedValue(), "projekt") &&
            Valideringsklass2.listidArValt(lstAllaPartners.getSelectedValue(), "partner")) {
            
            try {
                String valtProjekt = lstMinaProjekt.getSelectedValue();
                String valdPartner = lstAllaPartners.getSelectedValue();

                // Hämtar unika ID:n från databasen baserat på namnen
                String pId = idb.fetchSingle("SELECT pid FROM projekt WHERE projektnamn = '" + valtProjekt + "'");
                String partnerId = idb.fetchSingle("SELECT pid FROM partner WHERE namn = '" + valdPartner + "'");

                // Validerar att ID:n existerar och är korrekt formaterade 
                if (Valideringsklass2.arGiltigtId(pId) && Valideringsklass2.arGiltigtId(partnerId)) {
                    idb.delete("DELETE FROM projekt_partner WHERE pid = " + pId + " AND partner_pid = " + partnerId);
                    JOptionPane.showMessageDialog(this, "Kopplingen mellan " + valtProjekt + " och " + valdPartner + " är nu borttagen.");
                }

            } catch (InfException ex) {
                // Fångar upp databasfel så att applikationen inte kraschar
                JOptionPane.showMessageDialog(this, "Ett tekniskt fel uppstod vid borttagning: " + ex.getMessage());
            }
        }

    }//GEN-LAST:event_btnTaBortActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKoppla;
    private javax.swing.JButton btnTaBort;
    private javax.swing.JButton btnTillbaka;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> lstAllaPartners;
    private javax.swing.JList<String> lstMinaProjekt;
    private javax.swing.JPanel pnlMain;
    // End of variables declaration//GEN-END:variables
}
