 /*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import oru.inf.InfDB;
import oru.inf.InfException;

/**
 *
 * @author Lucy Alp, Olivia Collin, Mikaela Ak, Elin Jugås
 */
public class Inlogg extends javax.swing.JFrame {

    private InfDB idb;

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Inlogg.class.getName());

    /**
     * Creates new form Inlogg
     */
    public Inlogg(InfDB idb) {
        this.idb = idb;
        initComponents();
        lblFelMeddelande.setVisible(false);
    }

    public void loggaIn(String ePost, String Lösenord) {

    }

    public int test() {
        int x = 1;
        return x;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        lblEpost = new javax.swing.JLabel();
        lblLosenord = new javax.swing.JLabel();
        tfEpost = new javax.swing.JTextField();
        tfLosenord = new javax.swing.JTextField();
        lblFelMeddelande = new javax.swing.JLabel();
        btnLoggaIn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jTextField2.setText("jTextField2");

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblEpost.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblEpost.setText("E-post");

        lblLosenord.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblLosenord.setText("Lösenord");

        lblFelMeddelande.setForeground(new java.awt.Color(255, 51, 51));
        lblFelMeddelande.setText("Felaktig epost eller lösnord");

        btnLoggaIn.setBackground(new java.awt.Color(0, 153, 255));
        btnLoggaIn.setText("Logga in");
        btnLoggaIn.addActionListener(this::btnLoggaInActionPerformed);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 255));
        jLabel1.setText("SDG SWEDEN");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo_globala_malen_horizontell-1-1600x486.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(174, 174, 174)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEpost)
                            .addComponent(lblLosenord))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfLosenord, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfEpost, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblFelMeddelande))
                        .addGap(20, 20, 20)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(114, 114, 114))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnLoggaIn)
                        .addGap(192, 192, 192))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfEpost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEpost))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfLosenord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLosenord))
                .addGap(29, 29, 29)
                .addComponent(lblFelMeddelande)
                .addGap(29, 29, 29)
                .addComponent(btnLoggaIn)
                .addContainerGap(117, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoggaInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoggaInActionPerformed
        String ePost = tfEpost.getText();
        String losen = tfLosenord.getText();
        Valideringsklass2.kontrolleraInlogg(idb, ePost, losen, this, lblFelMeddelande);
    }//GEN-LAST:event_btnLoggaInActionPerformed


 
    
         public void run() {
         new Inlogg(idb).setVisible(true);
            }

        
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLoggaIn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel lblEpost;
    private javax.swing.JLabel lblFelMeddelande;
    private javax.swing.JLabel lblLosenord;
    private javax.swing.JTextField tfEpost;
    private javax.swing.JTextField tfLosenord;
    // End of variables declaration//GEN-END:variables

}