/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import oru.inf.InfDB;
import oru.inf.InfException;

/**
 *
 * @author User
 */
//Klass för projektchefen huvudmeny
public class MenyProjektChef extends javax.swing.JFrame {

    private InfDB idb;
    private String inloggadEpost;
    private int aid;

    // Instansvariabler för databasanslutning och inloggning
    private String fornamn;
    private String efternamn;
    private String adress;
    private String telefon;

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MenyProjektChef.class.getName());

    /**
     * Creates new form MenyProjektChef
     */
    public MenyProjektChef(InfDB idb, String inloggadEpost) {
        this.idb = idb;
        this.inloggadEpost = inloggadEpost;
        initComponents();

        //Hmptar data från databasen och informationstext
        lbInloggadAnvandare.setText("Inloggad som: " + inloggadEpost);
        hamtaAid();
        fyllProfilFalt();
    }

    // Hämtar ansätllnings-ID baserat på e-post
    private void hamtaAid() {
        try {
            // Hämtar AID för den person som har den inloggade e-posten
            String fraga = "SELECT aid FROM anstalld WHERE epost = '" + inloggadEpost + "'";
            String svar = idb.fetchSingle(fraga);
            if (svar != null) {
                aid = Integer.parseInt(svar);
            }
        } catch (InfException ex) {
            System.out.println("Fel vid hämtning av AID: " + ex.getMessage());
        }
    }

    //Hämtar all information om den inloggade från tabellen anställd och placerar det i textfälten.
    public void fyllProfilFalt() {
        try {
            // Vi använder variabeln inloggadEpost (String) istället för en Label
            String fraga = "SELECT * FROM anstalld WHERE epost = '" + inloggadEpost + "'";
            java.util.HashMap<String, String> rad = idb.fetchRow(fraga);

            if (rad != null) {
                txtAdress.setText(rad.get("adress"));
                txtEpost.setText(rad.get("epost"));
                txtTelefon.setText(rad.get("telefon"));
                txtLosenord.setText(rad.get("losenord"));

                // Förnamn och efternamn till labeln
                lblNamn.setText(rad.get("fornamn") + " " + rad.get("efternamn"));
            }
        } catch (InfException ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "Kunde inte ladda profil: " + ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        lbRubtik = new javax.swing.JLabel();
        lbInloggadAnvandare = new javax.swing.JLabel();
        btnLoggaUt = new javax.swing.JButton();
        btnGåTillAdmin = new javax.swing.JButton();
        btnGåTillStatistik = new javax.swing.JButton();
        pnlMinProfil = new javax.swing.JPanel();
        lblAdress = new javax.swing.JLabel();
        lblTelefon = new javax.swing.JLabel();
        lblEpost = new javax.swing.JLabel();
        lblLosenord = new javax.swing.JLabel();
        txtAdress = new javax.swing.JTextField();
        txtTelefon = new javax.swing.JTextField();
        txtEpost = new javax.swing.JTextField();
        txtLosenord = new javax.swing.JPasswordField();
        lblNamn = new javax.swing.JLabel();
        btnSparaUppgifter = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        btnVisaMal = new javax.swing.JButton();
        btnVisaPersonal = new javax.swing.JButton();
        btnHanteraHandlaggare = new javax.swing.JButton();
        btnVisaStatistik = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Projektstatistik");
        setBounds(new java.awt.Rectangle(0, 10, 0, 0));

        lbRubtik.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lbRubtik.setText("Välkommen projektchef!");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbRubtik, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbRubtik, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lbInloggadAnvandare.setText("Inloggad som: epost@doman.se");

        btnLoggaUt.setText("Logga ut");
        btnLoggaUt.addActionListener(this::btnLoggaUtActionPerformed);

        btnGåTillAdmin.setText("Projektaministration");
        btnGåTillAdmin.addActionListener(this::btnGåTillAdminActionPerformed);

        btnGåTillStatistik.setText("Visa projektstatistik");
        btnGåTillStatistik.addActionListener(this::btnGåTillStatistikActionPerformed);

        pnlMinProfil.setBorder(javax.swing.BorderFactory.createTitledBorder("Min Profil"));
        pnlMinProfil.setToolTipText("");

        lblAdress.setText("Adress:");

        lblTelefon.setText("Telefon:");

        lblEpost.setText("E-post:");

        lblLosenord.setText("Lösenord:");

        txtAdress.setText("jTextField1");

        txtTelefon.setText("jTextField2");

        txtEpost.setText("jTextField3");

        txtLosenord.setText("jPasswordField1");

        lblNamn.setText("jLabel1");

        btnSparaUppgifter.setText("Spara uppgifter");
        btnSparaUppgifter.addActionListener(this::btnSparaUppgifterActionPerformed);

        javax.swing.GroupLayout pnlMinProfilLayout = new javax.swing.GroupLayout(pnlMinProfil);
        pnlMinProfil.setLayout(pnlMinProfilLayout);
        pnlMinProfilLayout.setHorizontalGroup(
            pnlMinProfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMinProfilLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMinProfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNamn, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlMinProfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnSparaUppgifter)
                        .addGroup(pnlMinProfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pnlMinProfilLayout.createSequentialGroup()
                                .addComponent(lblLosenord)
                                .addGap(18, 18, 18)
                                .addComponent(txtLosenord, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE))
                            .addGroup(pnlMinProfilLayout.createSequentialGroup()
                                .addGroup(pnlMinProfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblAdress)
                                    .addComponent(lblTelefon)
                                    .addComponent(lblEpost))
                                .addGap(29, 29, 29)
                                .addGroup(pnlMinProfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtAdress, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                                    .addComponent(txtTelefon)
                                    .addComponent(txtEpost))))))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        pnlMinProfilLayout.setVerticalGroup(
            pnlMinProfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMinProfilLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(lblNamn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlMinProfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAdress)
                    .addComponent(txtAdress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(pnlMinProfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTelefon)
                    .addComponent(txtTelefon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(pnlMinProfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEpost, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEpost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(pnlMinProfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLosenord)
                    .addComponent(txtLosenord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnSparaUppgifter))
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 255));
        jLabel1.setText("SDG SWEDEN");

        jButton1.setText("Partnerhantering");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        btnVisaMal.setText("Hållbarhetsmålen");
        btnVisaMal.addActionListener(this::btnVisaMalActionPerformed);

        btnVisaPersonal.setText("Avdelningspersonal");
        btnVisaPersonal.addActionListener(this::btnVisaPersonalActionPerformed);

        btnHanteraHandlaggare.setText("Hantera handläggare");
        btnHanteraHandlaggare.addActionListener(this::btnHanteraHandlaggareActionPerformed);

        btnVisaStatistik.setText("Se statistik per land");
        btnVisaStatistik.addActionListener(this::btnVisaStatistikActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnVisaStatistik, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(btnHanteraHandlaggare, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnVisaPersonal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnVisaMal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnGåTillStatistik, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnGåTillAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbInloggadAnvandare))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnLoggaUt))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(pnlMinProfil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(lbInloggadAnvandare)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnGåTillAdmin)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnGåTillStatistik, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnVisaMal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnVisaPersonal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnHanteraHandlaggare)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnVisaStatistik)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(pnlMinProfil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)))
                .addComponent(btnLoggaUt)
                .addGap(10, 10, 10))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Loggar ut användaren genom att stänga nuvarande fönster och öppnar inloggningen. 
    private void btnLoggaUtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoggaUtActionPerformed
        this.dispose();
        Inlogg fonster = new Inlogg(idb);
        fonster.setLocationRelativeTo(null);
        fonster.setVisible(true);
    }//GEN-LAST:event_btnLoggaUtActionPerformed

    //Kommer till fönsret för projektadministration.
    //Skickar med aid så att fönstret vet vilken chef som är inloggad.
    private void btnGåTillAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGåTillAdminActionPerformed
        ProjektchefProjektAdministration adminFonster = new ProjektchefProjektAdministration(idb, aid, inloggadEpost);
        adminFonster.setLocationRelativeTo(null);
        adminFonster.setVisible(true);

        this.dispose();

    }//GEN-LAST:event_btnGåTillAdminActionPerformed
//Kommer till fönstret för projektstatistik. 
    private void btnGåTillStatistikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGåTillStatistikActionPerformed
ProjektchefProjektStatistik statistikFonster = new ProjektchefProjektStatistik(idb, aid, inloggadEpost);
        statistikFonster.setLocationRelativeTo(null);
statistikFonster.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_btnGåTillStatistikActionPerformed

    //Hämtar värden från textfältet och uppdaterar med de nya uppgifterna
    private void btnSparaUppgifterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSparaUppgifterActionPerformed
        try {
            //Hämtar text och tar bort eventuella mellansalag i början/Slutet
            String nyAdress = txtAdress.getText().trim();
            String nyTele = txtTelefon.getText().trim();
            String nyttLosen = new String(txtLosenord.getPassword());
// validering
            if (nyAdress.isEmpty() || nyTele.isEmpty() || nyttLosen.isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(this, "Alla fält måste vara ifyllda!");
                return;
            }
// SQL fråga för att uppdatera progilen
            String sql = "UPDATE anstalld SET adress = '" + nyAdress + "', telefon = '" + nyTele + "', losenord = '" + nyttLosen + "' WHERE epost = '" + inloggadEpost + "'";

            idb.update(sql);
            javax.swing.JOptionPane.showMessageDialog(this, "Dina uppgifter har uppdaterats!");
            fyllProfilFalt(); // uååaderar fälte fr att visa de sparade ändringarna

        } catch (InfException ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "Databasfel: " + ex.getMessage());
        }

    }//GEN-LAST:event_btnSparaUppgifterActionPerformed

    //öppnar fönstret för partnerhantering
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        ProjektchefPartneradministration partnerFonster = new ProjektchefPartneradministration(idb, inloggadEpost);
        partnerFonster.setLocationRelativeTo(null);
        partnerFonster.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_jButton1ActionPerformed
// Öppnar fönstret fr Hållbarhetsmålen
    private void btnVisaMalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVisaMalActionPerformed

        
        hallbarhetsmal malFonster = new hallbarhetsmal(idb, inloggadEpost);
        malFonster.setLocationRelativeTo(this);
        malFonster.setVisible(true);

       
    }//GEN-LAST:event_btnVisaMalActionPerformed
// Öppnar personalöversikten för projektchefen
    private void btnVisaPersonalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVisaPersonalActionPerformed
        ProjektchefPersonal personalFonster = new ProjektchefPersonal(idb, inloggadEpost);
        personalFonster.setLocationRelativeTo(null);
        personalFonster.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_btnVisaPersonalActionPerformed
//Öppnar hantering av handläggare
    private void btnHanteraHandlaggareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHanteraHandlaggareActionPerformed
        ProjektchefHandläggare handlaggareFonster = new ProjektchefHandläggare(idb, inloggadEpost);
        handlaggareFonster.setLocationRelativeTo(null);
        handlaggareFonster.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnHanteraHandlaggareActionPerformed

    private void btnVisaStatistikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVisaStatistikActionPerformed
      new ProjektchefStatistikLand(idb, inloggadEpost).setVisible(true);
      this.dispose();
    }//GEN-LAST:event_btnVisaStatistikActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGåTillAdmin;
    private javax.swing.JButton btnGåTillStatistik;
    private javax.swing.JButton btnHanteraHandlaggare;
    private javax.swing.JButton btnLoggaUt;
    private javax.swing.JButton btnSparaUppgifter;
    private javax.swing.JButton btnVisaMal;
    private javax.swing.JButton btnVisaPersonal;
    private javax.swing.JButton btnVisaStatistik;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lbInloggadAnvandare;
    private javax.swing.JLabel lbRubtik;
    private javax.swing.JLabel lblAdress;
    private javax.swing.JLabel lblEpost;
    private javax.swing.JLabel lblLosenord;
    private javax.swing.JLabel lblNamn;
    private javax.swing.JLabel lblTelefon;
    private javax.swing.JPanel pnlMinProfil;
    private javax.swing.JTextField txtAdress;
    private javax.swing.JTextField txtEpost;
    private javax.swing.JPasswordField txtLosenord;
    private javax.swing.JTextField txtTelefon;
    // End of variables declaration//GEN-END:variables

}
