    /*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import oru.inf.InfDB;
import oru.inf.InfException; 

public class MenyHandläggare extends javax.swing.JFrame {
    private InfDB idb;
    private String inloggadAnvandare;
    private javax.swing.JFrame previousFrame; 
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MenyHandläggare.class.getName());

    /**
     * skapaar menyn i konstruktorn vid inloggning
     */

    public MenyHandläggare(InfDB idb, String inloggadAnvandare) {
   
    this.idb = idb;
    this.inloggadAnvandare = inloggadAnvandare;
    initComponents();
    lblInloggad.setText("Inloggad som: " + inloggadAnvandare);    
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNamn = new javax.swing.JLabel();
        lblInloggad = new javax.swing.JLabel();
        minaUppgifter = new javax.swing.JButton();
        minaProjekt = new javax.swing.JButton();
        loggaUt = new javax.swing.JButton();
        hallbarhetsmål = new javax.swing.JButton();
        personal = new javax.swing.JButton();
        sammarbetsPartners = new javax.swing.JButton();
        avdelningsProjekt = new javax.swing.JButton();
        sokProjekt = new javax.swing.JButton();
        sokHandlaggare = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNamn.setBackground(new java.awt.Color(204, 204, 204));
        getContentPane().add(lblNamn, new org.netbeans.lib.awtextra.AbsoluteConstraints(408, 9, 167, 18));

        lblInloggad.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblInloggad.setText("Inloggad som:  ");
        getContentPane().add(lblInloggad, new org.netbeans.lib.awtextra.AbsoluteConstraints(-80, 10, 340, -1));

        minaUppgifter.setText("Mina uppgifter");
        minaUppgifter.addActionListener(this::minaUppgifterActionPerformed);
        getContentPane().add(minaUppgifter, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 190, -1));

        minaProjekt.setText("Mina projekt");
        minaProjekt.addActionListener(this::minaProjektActionPerformed);
        getContentPane().add(minaProjekt, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 190, -1));

        loggaUt.setText("Logga ut");
        loggaUt.addActionListener(this::loggaUtActionPerformed);
        getContentPane().add(loggaUt, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, -1, -1));

        hallbarhetsmål.setText("Hållbarhetsmålen");
        hallbarhetsmål.addActionListener(this::hallbarhetsmålActionPerformed);
        getContentPane().add(hallbarhetsmål, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 190, -1));

        personal.setText("Personal");
        personal.addActionListener(this::personalActionPerformed);
        getContentPane().add(personal, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 190, -1));

        sammarbetsPartners.setText("Sammarbets Partners");
        sammarbetsPartners.addActionListener(this::sammarbetsPartnersActionPerformed);
        getContentPane().add(sammarbetsPartners, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 190, -1));

        avdelningsProjekt.setText("Avdelnings projekt");
        avdelningsProjekt.addActionListener(this::avdelningsProjektActionPerformed);
        getContentPane().add(avdelningsProjekt, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 190, -1));

        sokProjekt.setText("Sök projekt");
        sokProjekt.addActionListener(this::sokProjektActionPerformed);
        getContentPane().add(sokProjekt, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 190, -1));

        sokHandlaggare.setText("Sök handläggare");
        sokHandlaggare.addActionListener(this::sokHandlaggareActionPerformed);
        getContentPane().add(sokHandlaggare, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 190, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void minaUppgifterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minaUppgifterActionPerformed
       new handlaggarUppgifter(idb, inloggadAnvandare).setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_minaUppgifterActionPerformed

    private void minaProjektActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minaProjektActionPerformed

       new HandlaggareProjekt(idb, inloggadAnvandare).setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_minaProjektActionPerformed

    private void hallbarhetsmålActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hallbarhetsmålActionPerformed
    new Hallbarhetsmal(idb, inloggadAnvandare, previousFrame).setVisible(true);
    this.setVisible(false);
    }//GEN-LAST:event_hallbarhetsmålActionPerformed

    private void loggaUtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loggaUtActionPerformed
        new Inlogg(idb).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_loggaUtActionPerformed

    private void sammarbetsPartnersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sammarbetsPartnersActionPerformed
    new HandlaggarePartner(idb, inloggadAnvandare).setVisible(true);
    this.setVisible(false);
    }//GEN-LAST:event_sammarbetsPartnersActionPerformed

    private void avdelningsProjektActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_avdelningsProjektActionPerformed
        
        new HandlaggareAvdProjekt(idb, inloggadAnvandare).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_avdelningsProjektActionPerformed

    private void personalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_personalActionPerformed
       new HandläggarePersonal(idb, inloggadAnvandare).setVisible(true);
       this.setVisible(false);
    
    
    }//GEN-LAST:event_personalActionPerformed

    private void sokProjektActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sokProjektActionPerformed

    new SökProjektDatum(idb, inloggadAnvandare).setVisible(true);
    this.dispose(); // Stänger menyn
    }//GEN-LAST:event_sokProjektActionPerformed

    private void sokHandlaggareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sokHandlaggareActionPerformed
      new SokHandlaggare(idb, inloggadAnvandare).setVisible(true);
      this.setVisible(false);
    }//GEN-LAST:event_sokHandlaggareActionPerformed



    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton avdelningsProjekt;
    private javax.swing.JButton hallbarhetsmål;
    private javax.swing.JLabel lblInloggad;
    private javax.swing.JLabel lblNamn;
    private javax.swing.JButton loggaUt;
    private javax.swing.JButton minaProjekt;
    private javax.swing.JButton minaUppgifter;
    private javax.swing.JButton personal;
    private javax.swing.JButton sammarbetsPartners;
    private javax.swing.JButton sokHandlaggare;
    private javax.swing.JButton sokProjekt;
    // End of variables declaration//GEN-END:variables


}
    






