/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import oru.inf.InfDB;
import oru.inf.InfException;
/**
 *
 * @author User
 */
public class MenyProjektChef extends javax.swing.JFrame {
    private InfDB idb;
    private String inloggadEpost;
    private int aid;
    

    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MenyProjektChef.class.getName());

    /**
     * Creates new form MenyProjektChef
     */
    public MenyProjektChef(InfDB idb, String inloggadEpost) {
        this.idb = idb;
        this.inloggadEpost = inloggadEpost;
        initComponents();
        
        lbInloggadAnvandare.setText("Inloggad som: " + inloggadEpost);
        hamtaAid();
      fyllProjektValjare();
    }
  
 private void hamtaAid() {
        try {
            String sql = "SELECT aid FROM anstalld WHERE epost = '" + inloggadEpost + "'";
            String svar = idb.fetchSingle(sql);
            if (svar != null) {
                aid = Integer.parseInt(svar);
                System.out.println("Hittade AID: " + aid);
            }
        } catch (InfException e) {
            System.out.println("Fel vid hämtning av aid: " + e.getMessage());
        } 
    }  
    
    private void visaKostnadsStatistik() {
    try {
        // SQL för att summera kostnaden för alla projekt där chefen är/har varit ansvarig
        String sql = "SELECT SUM(kostnad) FROM projekt WHERE projektchef = " + aid;
        String totalKostnad = idb.fetchSingle(sql);
        
        if (totalKostnad != null) {
            System.out.println("Total kostnad för dina projekt: " + totalKostnad);
            // Här kan du t.ex. visa resultatet i en JOptionPane eller en JLabel
        } else {
            System.out.println("Ingen kostnad registrerad.");
        }
    } catch (InfException ex) {
        System.out.println("Fel vid hämtning av kostnad: " + ex.getMessage());
    }
    
 }
   private void fyllProjektValjare() {
    try {
        cmbMinaProjekt.removeAllItems(); 
        String sql = "SELECT titel FROM projekt WHERE projektchef = " + aid;
        java.util.ArrayList<String> projektLista = idb.fetchColumn(sql);

        if (projektLista != null && !projektLista.isEmpty()) {
            for (String titel : projektLista) {
                cmbMinaProjekt.addItem(titel);
            }
        } else {
            cmbMinaProjekt.addItem("Inga projekt hittades");
            System.out.println("DEBUG: Inga projekt hittades för AID: " + aid);
        }
    } catch (InfException ex) {
        System.out.println("Fel: " + ex.getMessage());
    }
 
    

    
}

  
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        lbRubtik = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cmbMinaProjekt = new javax.swing.JComboBox<>();
        btnHanteraPersonal = new javax.swing.JButton();
        btnHanteraPartners = new javax.swing.JButton();
        btnAndraUppgifter = new javax.swing.JButton();
        lbInloggadAnvandare = new javax.swing.JLabel();
        btnLoggaUt = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbRubtik.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lbRubtik.setText("Projektledarpanel");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbRubtik, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(232, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbRubtik, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Projektadministration"));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("Välj projekt att hantera");
        jPanel2.add(jLabel1, new java.awt.GridBagConstraints());

        cmbMinaProjekt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbMinaProjekt.addActionListener(this::cmbMinaProjektActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.ipady = 1;
        jPanel2.add(cmbMinaProjekt, gridBagConstraints);

        btnHanteraPersonal.setFont(new java.awt.Font("SansSerif", 0, 10)); // NOI18N
        btnHanteraPersonal.setText("Hantera Personal");
        jPanel2.add(btnHanteraPersonal, new java.awt.GridBagConstraints());

        btnHanteraPartners.setFont(new java.awt.Font("SansSerif", 0, 10)); // NOI18N
        btnHanteraPartners.setText("Hantera partners");
        btnHanteraPartners.addActionListener(this::btnHanteraPartnersActionPerformed);
        jPanel2.add(btnHanteraPartners, new java.awt.GridBagConstraints());

        btnAndraUppgifter.setFont(new java.awt.Font("SansSerif", 0, 10)); // NOI18N
        btnAndraUppgifter.setText("Ändra uppgifter");
        btnAndraUppgifter.addActionListener(this::btnAndraUppgifterActionPerformed);
        jPanel2.add(btnAndraUppgifter, new java.awt.GridBagConstraints());

        lbInloggadAnvandare.setText("Inloggad som: epost@doman.se");

        btnLoggaUt.setText("Logga ut");
        btnLoggaUt.addActionListener(this::btnLoggaUtActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnLoggaUt)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lbInloggadAnvandare, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbInloggadAnvandare, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(12, 12, 12)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 111, Short.MAX_VALUE)
                .addComponent(btnLoggaUt)
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbMinaProjektActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbMinaProjektActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbMinaProjektActionPerformed

    private void btnAndraUppgifterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAndraUppgifterActionPerformed
        String valtProjekt = (String) cmbMinaProjekt.getSelectedItem(); 
        if (valtProjekt != null && !valtProjekt.equals("Inga projekt hittades")) {
        // Här skapar du nästa fönster, t.ex:
        // new RedigeraProjekt(idb, valtProjekt).setVisible(true);
        System.out.println("Öppnar redigering för: " + valtProjekt);
    } else {
        javax.swing.JOptionPane.showMessageDialog(this, "Välj ett projekt i listan först!");
     }
        
    }//GEN-LAST:event_btnAndraUppgifterActionPerformed

    private void btnHanteraPartnersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHanteraPartnersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHanteraPartnersActionPerformed

    private void btnLoggaUtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoggaUtActionPerformed
     this.dispose(); // Stänger nuvarande fönster
new Inlogg(idb).setVisible(true); // Öppnar inloggningen igen// TODO add your handling code here:
    }//GEN-LAST:event_btnLoggaUtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAndraUppgifter;
    private javax.swing.JButton btnHanteraPartners;
    private javax.swing.JButton btnHanteraPersonal;
    private javax.swing.JButton btnLoggaUt;
    private javax.swing.JComboBox<String> cmbMinaProjekt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbInloggadAnvandare;
    private javax.swing.JLabel lbRubtik;
    // End of variables declaration//GEN-END:variables

}
