/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import oru.inf.InfDB;
import oru.inf.InfException;
/**
 *
 * @author User
 */
public class MenyProjektChef extends javax.swing.JFrame {
    private InfDB idb;
    private String inloggadEpost;
    private int aid;
    
private String fornamn;
private String efternamn;
private String adress;
private String telefon;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MenyProjektChef.class.getName());

    /**
     * Creates new form MenyProjektChef
     */
    public MenyProjektChef(InfDB idb, String inloggadEpost) {
        this.idb = idb;
        this.inloggadEpost = inloggadEpost;
        initComponents();
        
        lbInloggadAnvandare.setText("Inloggad som: " + inloggadEpost);
        hamtaAid();
      fyllProfilFalt();
    }
    private void hamtaAid() {
    try {
        // Hämtar AID för den person som har den inloggade e-posten
        String fraga = "SELECT aid FROM anstalld WHERE epost = '" + inloggadEpost + "'";
        String svar = idb.fetchSingle(fraga);
        if (svar != null) {
            aid = Integer.parseInt(svar);
        }
    } catch (InfException ex) {
        System.out.println("Fel vid hämtning av AID: " + ex.getMessage());
    }
}
    
    public void fyllProfilFalt() {
    try {
        // Vi använder variabeln inloggadEpost (String) istället för en Label
        String fraga = "SELECT * FROM anstalld WHERE epost = '" + inloggadEpost + "'";
        java.util.HashMap<String, String> rad = idb.fetchRow(fraga);
        
        if (rad != null) {
            txtAdress.setText(rad.get("adress"));
            txtEpost.setText(rad.get("epost")); // Ofta satt till editable=false
            txtTelefon.setText(rad.get("telefon"));
            txtLosenord.setText(rad.get("losenord"));
            
            // lblNamn kan vara en rubrik överst i panelen
            lblNamn.setText(rad.get("fornamn") + " " + rad.get("efternamn"));
        }
    } catch (InfException ex) {
        javax.swing.JOptionPane.showMessageDialog(this, "Kunde inte ladda profil: " + ex.getMessage());
    }
}
  
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        lbRubtik = new javax.swing.JLabel();
        lbInloggadAnvandare = new javax.swing.JLabel();
        btnLoggaUt = new javax.swing.JButton();
        btnGåTillAdmin = new javax.swing.JButton();
        btnGåTillStatistik = new javax.swing.JButton();
        pnlMinProfil = new javax.swing.JPanel();
        lblAdress = new javax.swing.JLabel();
        lblTelefon = new javax.swing.JLabel();
        lblEpost = new javax.swing.JLabel();
        lblLosenord = new javax.swing.JLabel();
        txtAdress = new javax.swing.JTextField();
        txtTelefon = new javax.swing.JTextField();
        txtEpost = new javax.swing.JTextField();
        txtLosenord = new javax.swing.JPasswordField();
        lblNamn = new javax.swing.JLabel();
        btnSparaUppgifter = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Projektstatistik");
        setBounds(new java.awt.Rectangle(0, 10, 0, 0));

        lbRubtik.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lbRubtik.setText("Välkommen projektchef!");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbRubtik, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbRubtik, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lbInloggadAnvandare.setText("Inloggad som: epost@doman.se");

        btnLoggaUt.setText("Logga ut");
        btnLoggaUt.addActionListener(this::btnLoggaUtActionPerformed);

        btnGåTillAdmin.setText("Projektaministration");
        btnGåTillAdmin.addActionListener(this::btnGåTillAdminActionPerformed);

        btnGåTillStatistik.setText("Visa Statistik");
        btnGåTillStatistik.addActionListener(this::btnGåTillStatistikActionPerformed);

        pnlMinProfil.setBorder(javax.swing.BorderFactory.createTitledBorder("Min Profil"));
        pnlMinProfil.setToolTipText("");

        lblAdress.setText("Adress:");

        lblTelefon.setText("Telefon:");

        lblEpost.setText("E-post:");

        lblLosenord.setText("Lösenord:");

        txtAdress.setText("jTextField1");

        txtTelefon.setText("jTextField2");

        txtEpost.setText("jTextField3");

        txtLosenord.setText("jPasswordField1");

        lblNamn.setText("jLabel1");

        btnSparaUppgifter.setText("Spara uppgifter");
        btnSparaUppgifter.addActionListener(this::btnSparaUppgifterActionPerformed);

        javax.swing.GroupLayout pnlMinProfilLayout = new javax.swing.GroupLayout(pnlMinProfil);
        pnlMinProfil.setLayout(pnlMinProfilLayout);
        pnlMinProfilLayout.setHorizontalGroup(
            pnlMinProfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMinProfilLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMinProfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNamn, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlMinProfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnSparaUppgifter)
                        .addGroup(pnlMinProfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pnlMinProfilLayout.createSequentialGroup()
                                .addComponent(lblLosenord)
                                .addGap(18, 18, 18)
                                .addComponent(txtLosenord, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE))
                            .addGroup(pnlMinProfilLayout.createSequentialGroup()
                                .addGroup(pnlMinProfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblAdress)
                                    .addComponent(lblTelefon)
                                    .addComponent(lblEpost))
                                .addGap(29, 29, 29)
                                .addGroup(pnlMinProfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtAdress, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                                    .addComponent(txtTelefon)
                                    .addComponent(txtEpost))))))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        pnlMinProfilLayout.setVerticalGroup(
            pnlMinProfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMinProfilLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(lblNamn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlMinProfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAdress)
                    .addComponent(txtAdress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(pnlMinProfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTelefon)
                    .addComponent(txtTelefon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(pnlMinProfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEpost, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEpost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(pnlMinProfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLosenord)
                    .addComponent(txtLosenord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnSparaUppgifter))
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 255));
        jLabel1.setText("SDG SWEDEN");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnGåTillAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                                    .addComponent(btnGåTillStatistik, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbInloggadAnvandare))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnLoggaUt))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(pnlMinProfil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(lbInloggadAnvandare)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addComponent(pnlMinProfil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnGåTillAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnGåTillStatistik, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27)
                .addComponent(btnLoggaUt)
                .addGap(10, 10, 10))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoggaUtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoggaUtActionPerformed
     this.dispose(); 
    Inlogg fonster = new Inlogg(idb);
    fonster.setLocationRelativeTo(null); // Detta centrerar fönstret på skärmen
    fonster.setVisible(true);
    }//GEN-LAST:event_btnLoggaUtActionPerformed

    private void btnGåTillAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGåTillAdminActionPerformed
    ProjektchefProjektAdministration adminFonster = new ProjektchefProjektAdministration(idb, aid);
    adminFonster.setVisible(true);
    adminFonster.setLocationRelativeTo(null);

    }//GEN-LAST:event_btnGåTillAdminActionPerformed

    private void btnGåTillStatistikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGåTillStatistikActionPerformed
    
        new projektledareVisaStatistik(idb, aid).setVisible(true);
    }//GEN-LAST:event_btnGåTillStatistikActionPerformed

    private void btnSparaUppgifterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSparaUppgifterActionPerformed
try {
        String nyAdress = txtAdress.getText().trim();
        String nyTele = txtTelefon.getText().trim();
        String nyttLosen = new String(txtLosenord.getPassword());

        if (nyAdress.isEmpty() || nyTele.isEmpty() || nyttLosen.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Alla fält måste vara ifyllda!");
            return;
        }

        String sql = "UPDATE anstalld SET adress = '" + nyAdress + "', telefon = '" + nyTele + "', losenord = '" + nyttLosen + "' WHERE epost = '" + inloggadEpost + "'";

        idb.update(sql);
        javax.swing.JOptionPane.showMessageDialog(this, "Dina uppgifter har uppdaterats!");
        fyllProfilFalt(); 

    } catch (InfException ex) {
        javax.swing.JOptionPane.showMessageDialog(this, "Databasfel: " + ex.getMessage());
    }
            
    }//GEN-LAST:event_btnSparaUppgifterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        }); 
    } 
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGåTillAdmin;
    private javax.swing.JButton btnGåTillStatistik;
    private javax.swing.JButton btnLoggaUt;
    private javax.swing.JButton btnSparaUppgifter;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lbInloggadAnvandare;
    private javax.swing.JLabel lbRubtik;
    private javax.swing.JLabel lblAdress;
    private javax.swing.JLabel lblEpost;
    private javax.swing.JLabel lblLosenord;
    private javax.swing.JLabel lblNamn;
    private javax.swing.JLabel lblTelefon;
    private javax.swing.JPanel pnlMinProfil;
    private javax.swing.JTextField txtAdress;
    private javax.swing.JTextField txtEpost;
    private javax.swing.JPasswordField txtLosenord;
    private javax.swing.JTextField txtTelefon;
    // End of variables declaration//GEN-END:variables

}
