    /*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import oru.inf.InfDB;
import oru.inf.InfException;
/**
 *
 * @author oliviacollin
 */
public class MenyHandläggare extends javax.swing.JFrame {
    private InfDB idb;
    private String inloggadAnvandare;
    
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MenyHandläggare.class.getName());

    /**
     * skapaar menyn efter inloggning
     */

    public MenyHandläggare(InfDB idb, String inloggadAnvandare) {
        initComponents();
        this.idb = idb;
        this.inloggadAnvandare = inloggadAnvandare;
        lblInloggad.setText("Inloggad som: " + inloggadAnvandare);    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNamn = new javax.swing.JLabel();
        lblInloggad = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNamn.setBackground(new java.awt.Color(204, 204, 204));
        getContentPane().add(lblNamn, new org.netbeans.lib.awtextra.AbsoluteConstraints(408, 9, 167, 18));

        lblInloggad.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblInloggad.setText("Inloggad som:  ");
        getContentPane().add(lblInloggad, new org.netbeans.lib.awtextra.AbsoluteConstraints(-80, 10, 177, -1));

        jButton2.setText("Mina projekt");
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(406, 71, -1, -1));

        jButton1.setText("Mina uppgifter");
        jButton1.addActionListener(this::jButton1ActionPerformed);
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, -1, -1));

        jButton3.setText("Mina projekt");
        jButton3.addActionListener(this::jButton3ActionPerformed);
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 70, -1, -1));

        jButton4.setText("Logga ut");
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       new handlaggarUppgifter(idb, inloggadAnvandare).setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
       new Handläggareprojekt(idb, inloggadAnvandare).setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed


    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel lblInloggad;
    private javax.swing.JLabel lblNamn;
    // End of variables declaration//GEN-END:variables


    }
    






