/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 * Klass för att hantera partners, se, ändra och följa upp
 * @author elinjugas
 */
import oru.inf.InfDB;
import oru.inf.InfException;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.DefaultListModel;
import javax.swing.table.DefaultTableModel;

public class ProjektchefPartneradministration extends javax.swing.JFrame {

    //Instansvariabler för databas, inloggning.
    private InfDB idb;
    private String nuvarandePartnerNamn; // Håller koll på vilken partner som redigeras just nu
    private String inloggadAnvandare;
    private String inloggadEpost;
    private String epost;

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ProjektchefPartneradministration.class.getName());

    /**
     * Creates new form ProjektchefPartneradministration
     */
    public ProjektchefPartneradministration(InfDB idb, String inloggadEpost) {
        initComponents();
        this.idb = idb;
        this.inloggadAnvandare = inloggadAnvandare;
        
        // Fyller listan till vänster med partners vid start
        fyllPartnerLista();
        this.epost = epost;
        this.inloggadEpost = inloggadEpost;

    }

    //Hämtar alla partnernamn från databasen och lägger dem i Jlist
    private void fyllPartnerLista() {
        try {
            DefaultListModel<String> model = new DefaultListModel<>();
            //Hämtar endast namnen för att visa i listan
            ArrayList<String> partners = idb.fetchColumn("SELECT namn FROM partner");

            if (partners != null) {
                for (String namn : partners) {
                    model.addElement(namn);
                }
            }
            lstPartners.setModel(model);
        } catch (InfException ex) {
            System.out.println("Hittade inga partners: " + ex.getMessage());
        }
    }
 
    //Hämtar detaljerad information om en specifik partner när man klickar i partner
    private void fyllPartnerUppgifter(String namn) {
        try {

            //SQL-fråga för att hämta all info om den valda personen
            String fraga = "SELECT * FROM partner WHERE namn = '" + namn + "'";
            HashMap<String, String> rad = idb.fetchRow(fraga);

            if (rad != null) {
                //Sparar namnet för att veta vilken rad som ska uppdateras senare

                //Sparar namnet i en variabel för att veta vilken rad som ska uppdateras senare
                nuvarandePartnerNamn = namn;

                //Sätter texterna i textfälten baserat på databasens värde
                txtNamn.setText(rad.get("namn"));
                txtKontakt.setText(rad.get("kontaktperson"));
                txtEpost.setText(rad.get("kontaktepost"));
                txtTelefon.setText(rad.get("telefon"));
                txtAdress.setText(rad.get("adress"));

                // 
                if (rad.containsKey("branch")) {
                    txtBransch.setText(rad.get("branch"));
                } else {
                    txtBransch.setText(rad.get("branch"));
                }
            }
        } catch (InfException ex) {
            System.out.println("Fel vid hämtning av uppgifter: " + ex.getMessage());
        }
    }

    //Hämtar projekt kopplade till partnern och visar dem i en tabell. 
    private void fyllProjektTabell(String namn) {
        try {

            //Använder Join för att koppla ihop tabellerna partner, projektpartner och projekt
            String fraga = "SELECT projekt.projektnamn, projekt.status, projekt.startdatum "
                    + "FROM projekt "
                    + "JOIN projekt_partner ON projekt.pid = projekt_partner.pid "
                    + "JOIN partner ON projekt_partner.partner_pid = partner.pid "
                    + "WHERE partner.namn = '" + namn + "'";

            ArrayList<HashMap<String, String>> rader = idb.fetchRows(fraga);
            DefaultTableModel model = (DefaultTableModel) tblPartnerProjekt.getModel();

            //Rensa tabellen innan ny data läggs till
            model.setRowCount(0);

            if (rader != null) {
                for (HashMap<String, String> rad : rader) {

                    model.addRow(new Object[]{
                        rad.get("projektnamn"),
                        rad.get("status"),
                        rad.get("startdatum")
                    });
                }
            }
        } catch (InfException ex) {
            System.out.println("Fel vid hämtning av projekt: " + ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblRubrik = new javax.swing.JLabel();
        pnlMain = new javax.swing.JPanel();
        pnlPartnerOchProjekt = new javax.swing.JPanel();
        pnlLista = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        lstPartners = new javax.swing.JList<>();
        pnlInnehall = new javax.swing.JPanel();
        tpnlPartnerOchProjekt = new javax.swing.JTabbedPane();
        pnlPartner = new javax.swing.JPanel();
        lblNamn = new javax.swing.JLabel();
        lblEpost = new javax.swing.JLabel();
        lblTelefon = new javax.swing.JLabel();
        lblKontakt = new javax.swing.JLabel();
        lblAdress = new javax.swing.JLabel();
        txtNamn = new javax.swing.JTextField();
        txtEpost = new javax.swing.JTextField();
        txtTelefon = new javax.swing.JTextField();
        txtKontakt = new javax.swing.JTextField();
        txtAdress = new javax.swing.JTextField();
        btmSpara = new javax.swing.JButton();
        lblBransch = new javax.swing.JLabel();
        txtBransch = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPartnerProjekt = new javax.swing.JTable();
        btnHanteraKopplingar = new javax.swing.JButton();
        btnTillbaka = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(51, 153, 255));
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setPreferredSize(new java.awt.Dimension(700, 500));

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));
        jPanel1.setForeground(new java.awt.Color(51, 153, 255));

        lblRubrik.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblRubrik.setForeground(new java.awt.Color(255, 255, 255));
        lblRubrik.setText("Partnerhantering");
        lblRubrik.setToolTipText("");

        pnlMain.setBackground(new java.awt.Color(51, 153, 255));

        pnlLista.setBorder(javax.swing.BorderFactory.createTitledBorder("Partners:"));
        pnlLista.setPreferredSize(new java.awt.Dimension(250, 333));

        lstPartners.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        lstPartners.addListSelectionListener(this::lstPartnersValueChanged);
        jScrollPane3.setViewportView(lstPartners);

        javax.swing.GroupLayout pnlListaLayout = new javax.swing.GroupLayout(pnlLista);
        pnlLista.setLayout(pnlListaLayout);
        pnlListaLayout.setHorizontalGroup(
            pnlListaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlListaLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );
        pnlListaLayout.setVerticalGroup(
            pnlListaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlListaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(123, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlInnehallLayout = new javax.swing.GroupLayout(pnlInnehall);
        pnlInnehall.setLayout(pnlInnehallLayout);
        pnlInnehallLayout.setHorizontalGroup(
            pnlInnehallLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlInnehallLayout.setVerticalGroup(
            pnlInnehallLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        lblNamn.setText("Namn:");

        lblEpost.setText("E-post:");

        lblTelefon.setText("Telefon:");

        lblKontakt.setText("Kontaktperson:");

        lblAdress.setText("Adress:");

        txtEpost.addActionListener(this::txtEpostActionPerformed);

        btmSpara.setText("Spara ändringar");
        btmSpara.addActionListener(this::btmSparaActionPerformed);

        lblBransch.setText("Bransch:");

        javax.swing.GroupLayout pnlPartnerLayout = new javax.swing.GroupLayout(pnlPartner);
        pnlPartner.setLayout(pnlPartnerLayout);
        pnlPartnerLayout.setHorizontalGroup(
            pnlPartnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPartnerLayout.createSequentialGroup()
                .addGroup(pnlPartnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlPartnerLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btmSpara))
                    .addGroup(pnlPartnerLayout.createSequentialGroup()
                        .addGroup(pnlPartnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlPartnerLayout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addGroup(pnlPartnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblAdress)
                                    .addComponent(lblBransch)))
                            .addGroup(pnlPartnerLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblKontakt))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPartnerLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(pnlPartnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblEpost)
                                    .addComponent(lblTelefon)
                                    .addComponent(lblNamn))))
                        .addGap(41, 41, 41)
                        .addGroup(pnlPartnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtAdress, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                            .addComponent(txtKontakt)
                            .addComponent(txtTelefon)
                            .addComponent(txtEpost)
                            .addComponent(txtNamn)
                            .addComponent(txtBransch))))
                .addGap(26, 26, 26))
        );
        pnlPartnerLayout.setVerticalGroup(
            pnlPartnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPartnerLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(pnlPartnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNamn)
                    .addComponent(txtNamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlPartnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEpost)
                    .addComponent(txtEpost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlPartnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTelefon)
                    .addComponent(txtTelefon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlPartnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblKontakt)
                    .addComponent(txtKontakt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlPartnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAdress)
                    .addComponent(txtAdress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlPartnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBransch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtBransch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(btmSpara)
                .addGap(13, 13, 13))
        );

        tpnlPartnerOchProjekt.addTab("Partneruppgifter", pnlPartner);

        tblPartnerProjekt.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Projektnamn", "Status", "Startdatum"
            }
        ));
        jScrollPane1.setViewportView(tblPartnerProjekt);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tpnlPartnerOchProjekt.addTab("Projektstatistik", jPanel5);

        javax.swing.GroupLayout pnlPartnerOchProjektLayout = new javax.swing.GroupLayout(pnlPartnerOchProjekt);
        pnlPartnerOchProjekt.setLayout(pnlPartnerOchProjektLayout);
        pnlPartnerOchProjektLayout.setHorizontalGroup(
            pnlPartnerOchProjektLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPartnerOchProjektLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlLista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tpnlPartnerOchProjekt, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlInnehall, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlPartnerOchProjektLayout.setVerticalGroup(
            pnlPartnerOchProjektLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPartnerOchProjektLayout.createSequentialGroup()
                .addGroup(pnlPartnerOchProjektLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPartnerOchProjektLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(tpnlPartnerOchProjekt)
                        .addGap(18, 18, 18))
                    .addGroup(pnlPartnerOchProjektLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pnlLista, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(pnlInnehall, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        btnHanteraKopplingar.setText("Hantera partners i projekt");
        btnHanteraKopplingar.addActionListener(this::btnHanteraKopplingarActionPerformed);

        btnTillbaka.setText("Tillbaka");
        btnTillbaka.addActionListener(this::btnTillbakaActionPerformed);

        javax.swing.GroupLayout pnlMainLayout = new javax.swing.GroupLayout(pnlMain);
        pnlMain.setLayout(pnlMainLayout);
        pnlMainLayout.setHorizontalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(pnlPartnerOchProjekt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMainLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnHanteraKopplingar)
                .addGap(18, 18, 18)
                .addComponent(btnTillbaka)
                .addGap(46, 46, 46))
        );
        pnlMainLayout.setVerticalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMainLayout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addComponent(pnlPartnerOchProjekt, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHanteraKopplingar)
                    .addComponent(btnTillbaka))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblRubrik, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblRubrik, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtEpostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEpostActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEpostActionPerformed

    private void btmSparaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmSparaActionPerformed
     //  Validera att en partner är vald i listan
    if (!Valideringsklass2.idArSatt(nuvarandePartnerNamn, "partner")) {
        return;
    }

    //  Kontrollera att obligatoriska fält är ifyllda
    if (!Valideringsklass2.textfaltHarVarde(txtNamn, "namn") ||
        !Valideringsklass2.textfaltHarVarde(txtEpost, "e-post") ||
        !Valideringsklass2.textfaltHarVarde(txtTelefon, "telefon") ||
        !Valideringsklass2.textfaltHarVarde(txtKontakt, "kontaktperson")) {
        return;
    }

    // Validera format med Regular Expressions (RegEx)
    if (!Valideringsklass2.arGiltigText(txtNamn, "namn") ||
        !Valideringsklass2.arGiltigEpost(txtEpost) ||
        !Valideringsklass2.arGiltigtTelefonnummer(txtTelefon) ||
        !Valideringsklass2.arGiltigText(txtKontakt, "kontaktperson")) {
        return;
    }

    // Om valideringen passerar, uppdatera databasen
    try {
        String nyttNamn = txtNamn.getText().trim();
        String epost = txtEpost.getText().trim();
        String tel = txtTelefon.getText().trim();
        String kontakt = txtKontakt.getText().trim();
        String adress = txtAdress.getText().trim();
        String bransch = txtBransch.getText().trim();

        String sql = "UPDATE partner SET "
                + "namn='" + nyttNamn + "', "
                + "kontaktepost='" + epost + "', "
                + "telefon='" + tel + "', "
                + "kontaktperson='" + kontakt + "', "
                + "adress='" + adress + "', "
                + "branch='" + bransch + "' "
                + "WHERE namn='" + nuvarandePartnerNamn + "'";

        idb.update(sql);
        
        // Bekräftelse till användaren (Krav: Användarhjälp)
        javax.swing.JOptionPane.showMessageDialog(this, "Ändringarna har sparats!");
        
        // Uppdatera GUI
        fyllPartnerLista();
        nuvarandePartnerNamn = nyttNamn;
        
    } catch (InfException ex) {
        javax.swing.JOptionPane.showMessageDialog(this, "Ett fel uppstod vid sparande: " + ex.getMessage());
    }
    
    }//GEN-LAST:event_btmSparaActionPerformed

    private void lstPartnersValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstPartnersValueChanged
        // Gör så att koden bara körs en gång och fyller flikarna 
        if (!evt.getValueIsAdjusting()) {
            String valtNamn = lstPartners.getSelectedValue();
            if (valtNamn != null) {
                fyllPartnerUppgifter(valtNamn);
                fyllProjektTabell(valtNamn);
            }
        }


    }//GEN-LAST:event_lstPartnersValueChanged

    //Går tillbaka till huvudmenyn för projektchefer
    private void btnTillbakaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTillbakaActionPerformed
        new MenyProjektChef(idb, inloggadEpost).setVisible(true);
        this.dispose(); //Stänger ner nuvarande fönster
    }//GEN-LAST:event_btnTillbakaActionPerformed

    //Öppnar fönstret för att lägga till eller ta bort partners från projekt
    private void btnHanteraKopplingarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHanteraKopplingarActionPerformed
        HanteraProjektPartners hantera = new HanteraProjektPartners(idb, inloggadEpost);
        hantera.setLocationRelativeTo(null);
        hantera.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnHanteraKopplingarActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btmSpara;
    private javax.swing.JButton btnHanteraKopplingar;
    private javax.swing.JButton btnTillbaka;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblAdress;
    private javax.swing.JLabel lblBransch;
    private javax.swing.JLabel lblEpost;
    private javax.swing.JLabel lblKontakt;
    private javax.swing.JLabel lblNamn;
    private javax.swing.JLabel lblRubrik;
    private javax.swing.JLabel lblTelefon;
    private javax.swing.JList<String> lstPartners;
    private javax.swing.JPanel pnlInnehall;
    private javax.swing.JPanel pnlLista;
    private javax.swing.JPanel pnlMain;
    private javax.swing.JPanel pnlPartner;
    private javax.swing.JPanel pnlPartnerOchProjekt;
    private javax.swing.JTable tblPartnerProjekt;
    private javax.swing.JTabbedPane tpnlPartnerOchProjekt;
    private javax.swing.JTextField txtAdress;
    private javax.swing.JTextField txtBransch;
    private javax.swing.JTextField txtEpost;
    private javax.swing.JTextField txtKontakt;
    private javax.swing.JTextField txtNamn;
    private javax.swing.JTextField txtTelefon;
    // End of variables declaration//GEN-END:variables
}
