/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import oru.inf.InfDB;
import oru.inf.InfException;

/**
 * Klass för att visa en lista över prsonal som arbetar på en avdelning
 * @author User
 */

public class ProjektchefPersonal extends javax.swing.JFrame {

    //Instansvariabler för databasanslutning och lagrar epost
    private InfDB idb;
    private String inloggadAnvandare;

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(HandläggarePersonal.class.getName());

    /**
     * Creates new form HandläggarePersonal
     */
    public ProjektchefPersonal(InfDB idb, String inloggadAnvandare) {
        this.idb = idb;
        this.inloggadAnvandare = inloggadAnvandare;
        initComponents();
        //Kör metoden som hämtar personelen direkt när fönstrt öppnas
        listaPersonalPaMinAvd();
    }

    //Metod som hämtar och visar alla anställda som tillhör samma avdelning
    public void listaPersonalPaMinAvd() {
     // Validera inmatning/tillstånd innan körning (Krav: All inmatning ska kontrolleras)
    if (!Valideringsklass2.idArSatt(inloggadAnvandare, "användare")) {
        return;
    }

    try {
        // Hämta avdelnings-ID
        String avdId = idb.fetchSingle("SELECT avdelning FROM anstalld WHERE epost = '" + inloggadAnvandare + "'");
        // Hämtar förnamn och efternamn på alla som har samma avdelnings-ID
        //Concat används för att få ihop namnen till en snygg sträng
        if (avdId != null) {
            String fraga = "SELECT CONCAT(fornamn , ' ' , efternamn) FROM anstalld WHERE avdelning = '" + avdId + "'";
            java.util.ArrayList<String> namnLista = idb.fetchColumn(fraga);

            // Om vi fick träffar, lägger in den i en Jlist via defaultList
            if (namnLista != null) {
                javax.swing.DefaultListModel<String> model = new javax.swing.DefaultListModel<>();
                for (String namn : namnLista) {
                    model.addElement(namn);
                }
                personalLista.setModel(model); // Kopplar modellen till den grafiska listan
            }
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Kunde inte hitta avdelning för den inloggade användaren.");
        }

        // Felmeddelande  om något strular
    } catch (InfException ex) {
        // Krav: Felmeddelanden ska hjälpa användaren och inte bara skrivas i konsolen
        javax.swing.JOptionPane.showMessageDialog(this, "Ett fel uppstod vid hämtning av personal: " + ex.getMessage());
        logger.log(java.util.logging.Level.SEVERE, null, ex);
    }   

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        personalLista = new javax.swing.JList<>();
        tillbakaTillMeny = new javax.swing.JButton();
        titel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 153, 242));

        jScrollPane1.setViewportView(personalLista);

        tillbakaTillMeny.setText("Tillbaka");
        tillbakaTillMeny.addActionListener(this::tillbakaTillMenyActionPerformed);

        titel.setText("Personal på din avdelning:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tillbakaTillMeny)
                            .addComponent(titel))
                        .addGap(0, 419, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titel)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(tillbakaTillMeny)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Körd när användaren klickar "Tillbaka" till huvudmenyn
    private void tillbakaTillMenyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tillbakaTillMenyActionPerformed
        new MenyProjektChef(idb, inloggadAnvandare).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_tillbakaTillMenyActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> personalLista;
    private javax.swing.JButton tillbakaTillMeny;
    private javax.swing.JLabel titel;
    // End of variables declaration//GEN-END:variables
}
