/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author elinjugas
 */

import oru.inf.InfDB;
import oru.inf.InfException;
import java.util.ArrayList;
import java.util.HashMap;


public class ProjektchefProjektAdministration extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ProjektchefProjektAdministration.class.getName());
private InfDB idDB;
private int aid;
private String projektnamn;
private String epost;
    /**
     * Creates new form ProjektchefAdministration
     */
   
    public ProjektchefProjektAdministration(InfDB idb,int aid, String epost) { 
    this.idDB = idb;
    this.aid = aid;
    this.epost = epost;
    initComponents();
    

    
    fyllProjektLista("SELECT projektnamn FROM projekt WHERE projektchef = " + aid);
    
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pnlLabel = new javax.swing.JPanel();
        lblProjektadministration = new javax.swing.JLabel();
        pnlMain = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        pnlVanster = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cbProjektVal = new javax.swing.JComboBox<>();
        lblStatusRubrik = new javax.swing.JLabel();
        lblBudgetRubrik = new javax.swing.JLabel();
        lblStartDatum = new javax.swing.JLabel();
        lblBeskrivning = new javax.swing.JLabel();
        lblSlutdatum = new javax.swing.JLabel();
        lblStatusInfo = new javax.swing.JLabel();
        lblBudgetInfo = new javax.swing.JLabel();
        lblStartDatumInfo = new javax.swing.JLabel();
        lblSlutDatumInfo = new javax.swing.JLabel();
        lblBeskrivningInfo = new javax.swing.JLabel();
        btnRedigeraProjektUppgifter = new javax.swing.JButton();
        btnSeKostnadsstatistik = new javax.swing.JButton();
        lblSokProjekt = new javax.swing.JLabel();
        lblSokProjektFran = new javax.swing.JLabel();
        lblSokProjektTill = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        btnFiltreraProjekt = new javax.swing.JButton();
        lblFiltreraPåStatus = new javax.swing.JLabel();
        cbStatusFilter = new javax.swing.JComboBox<>();
        btnFiltreraPaStatus = new javax.swing.JButton();
        btnTillbaka = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlLabel.setBackground(new java.awt.Color(51, 153, 255));

        lblProjektadministration.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblProjektadministration.setForeground(new java.awt.Color(255, 255, 255));
        lblProjektadministration.setText("PROJEKTADMINISTRATION");
        lblProjektadministration.setToolTipText("");

        javax.swing.GroupLayout pnlLabelLayout = new javax.swing.GroupLayout(pnlLabel);
        pnlLabel.setLayout(pnlLabelLayout);
        pnlLabelLayout.setHorizontalGroup(
            pnlLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLabelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lblProjektadministration)
                .addContainerGap(32502, Short.MAX_VALUE))
        );
        pnlLabelLayout.setVerticalGroup(
            pnlLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLabelLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lblProjektadministration)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        getContentPane().add(pnlLabel, java.awt.BorderLayout.NORTH);

        pnlMain.setLayout(new java.awt.GridLayout(1, 2, 25, 25));

        pnlVanster.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Mina Projekt", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Helvetica Neue", 0, 14))); // NOI18N

        jLabel1.setText("Mina projekt");

        cbProjektVal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbProjektVal.addActionListener(this::cbProjektValActionPerformed);

        lblStatusRubrik.setText("Status:");

        lblBudgetRubrik.setText("Budget:");

        lblStartDatum.setText("Startdatum:");

        lblBeskrivning.setText("Beskrivning:");

        lblSlutdatum.setText("Slutdatum:");

        lblStatusInfo.setText("jLabel2");

        lblBudgetInfo.setText("jLabel3");

        lblStartDatumInfo.setText("jLabel4");

        lblSlutDatumInfo.setText("jLabel5");

        lblBeskrivningInfo.setText("jLabel6");

        btnRedigeraProjektUppgifter.setText("Ändra projektuppgifter");
        btnRedigeraProjektUppgifter.addActionListener(this::btnRedigeraProjektUppgifterActionPerformed);

        btnSeKostnadsstatistik.setText("Se statistik");
        btnSeKostnadsstatistik.addActionListener(this::btnSeKostnadsstatistikActionPerformed);

        lblSokProjekt.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        lblSokProjekt.setText("Sök projekt (datum):");

        lblSokProjektFran.setText("Från:");

        lblSokProjektTill.setText("Till:");

        jTextField1.setText("jTextField1");
        jTextField1.setToolTipText("YYYY-MM-DD");

        jTextField2.setText("jTextField2");
        jTextField2.setToolTipText("YYY-MM-DD");

        btnFiltreraProjekt.setText("Filtrera");
        btnFiltreraProjekt.addActionListener(this::btnFiltreraProjektActionPerformed);

        lblFiltreraPåStatus.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        lblFiltreraPåStatus.setText("Filtrera på status:");

        cbStatusFilter.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Visa alla", "Planerat", "Pågående", "Avslutat", " " }));

        btnFiltreraPaStatus.setText("Filtrera");
        btnFiltreraPaStatus.addActionListener(this::btnFiltreraPaStatusActionPerformed);

        btnTillbaka.setText("Tillbaka");
        btnTillbaka.addActionListener(this::btnTillbakaActionPerformed);

        javax.swing.GroupLayout pnlVansterLayout = new javax.swing.GroupLayout(pnlVanster);
        pnlVanster.setLayout(pnlVansterLayout);
        pnlVansterLayout.setHorizontalGroup(
            pnlVansterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlVansterLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlVansterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlVansterLayout.createSequentialGroup()
                        .addComponent(lblStatusRubrik)
                        .addGap(43, 43, 43)
                        .addComponent(lblStatusInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlVansterLayout.createSequentialGroup()
                        .addComponent(lblBudgetRubrik)
                        .addGap(38, 38, 38)
                        .addComponent(lblBudgetInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlVansterLayout.createSequentialGroup()
                        .addGroup(pnlVansterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlVansterLayout.createSequentialGroup()
                                .addComponent(lblBeskrivning)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblStartDatumInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(40, 40, 40)
                                .addComponent(btnSeKostnadsstatistik, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlVansterLayout.createSequentialGroup()
                                .addComponent(lblSlutdatum)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblSlutDatumInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(pnlVansterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnTillbaka, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnRedigeraProjektUppgifter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addContainerGap())
                    .addGroup(pnlVansterLayout.createSequentialGroup()
                        .addGroup(pnlVansterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlVansterLayout.createSequentialGroup()
                                .addComponent(lblStartDatum)
                                .addGap(18, 18, 18)
                                .addComponent(lblBeskrivningInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlVansterLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbProjektVal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlVansterLayout.createSequentialGroup()
                                .addGroup(pnlVansterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblSokProjekt, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblFiltreraPåStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(pnlVansterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlVansterLayout.createSequentialGroup()
                                        .addComponent(lblSokProjektFran)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblSokProjektTill)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(cbStatusFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(pnlVansterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnFiltreraPaStatus)
                                    .addComponent(btnFiltreraProjekt))))
                        .addGap(0, 179, Short.MAX_VALUE))))
        );
        pnlVansterLayout.setVerticalGroup(
            pnlVansterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlVansterLayout.createSequentialGroup()
                .addContainerGap(91, Short.MAX_VALUE)
                .addGroup(pnlVansterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSokProjekt)
                    .addComponent(lblSokProjektFran)
                    .addComponent(lblSokProjektTill)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFiltreraProjekt))
                .addGap(30, 30, 30)
                .addGroup(pnlVansterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFiltreraPåStatus)
                    .addComponent(cbStatusFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFiltreraPaStatus))
                .addGap(28, 28, 28)
                .addGroup(pnlVansterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cbProjektVal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(pnlVansterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStatusRubrik)
                    .addComponent(lblStatusInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(pnlVansterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBudgetRubrik)
                    .addComponent(lblBudgetInfo))
                .addGap(18, 18, 18)
                .addGroup(pnlVansterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStartDatum)
                    .addComponent(lblBeskrivningInfo)
                    .addComponent(btnTillbaka))
                .addGap(18, 18, 18)
                .addGroup(pnlVansterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlVansterLayout.createSequentialGroup()
                        .addGroup(pnlVansterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnRedigeraProjektUppgifter)
                            .addComponent(lblSlutdatum)
                            .addComponent(lblSlutDatumInfo))
                        .addGap(18, 18, 18)
                        .addComponent(btnSeKostnadsstatistik)
                        .addGap(12, 12, 12))
                    .addGroup(pnlVansterLayout.createSequentialGroup()
                        .addGroup(pnlVansterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblBeskrivning)
                            .addComponent(lblStartDatumInfo))
                        .addGap(24, 24, 24))))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(pnlVanster, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32396, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(pnlVanster, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pnlMain.add(jPanel2);

        getContentPane().add(pnlMain, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

   
    private void btnFiltreraPaStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltreraPaStatusActionPerformed
        String status = cbStatusFilter.getSelectedItem().toString();
        String fraga;
        if (status.equals("Visa alla")) {
            fraga = "SELECT projektnamn FROM projekt";
        } else {
            fraga = "SELECT projektnamn FROM projekt WHERE status = '" + status + "'";
        }
        fyllProjektLista(fraga);
    }//GEN-LAST:event_btnFiltreraPaStatusActionPerformed

    private void btnFiltreraProjektActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltreraProjektActionPerformed
        String start = jTextField1.getText();
        String slut = jTextField2.getText();
        String fraga = "SELECT projektnamn FROM projekt WHERE startdatum >= '" + start + "' AND slutdatum <= '" + slut + "'";
        fyllProjektLista(fraga);

    }//GEN-LAST:event_btnFiltreraProjektActionPerformed

    private void btnRedigeraProjektUppgifterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRedigeraProjektUppgifterActionPerformed
    if (cbProjektVal.getSelectedItem() != null) {
        
    }
        String valtProjekt = cbProjektVal.getSelectedItem().toString();
     new ProjektchefRedigeraProjekt(idDB, valtProjekt).setVisible(true);
     this.dispose();
    }//GEN-LAST:event_btnRedigeraProjektUppgifterActionPerformed

    private void cbProjektValActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbProjektValActionPerformed
        if (cbProjektVal.getSelectedItem() != null) {
            try {
                String valtProjekt = cbProjektVal.getSelectedItem().toString();
                var rad = idDB.fetchRow("SELECT * FROM projekt WHERE projektnamn = '" + valtProjekt + "'");

                lblStatusInfo.setText(rad.get("status"));
                lblBudgetInfo.setText(rad.get("kostnad"));
                lblStartDatumInfo.setText(rad.get("startdatum"));
                lblSlutDatumInfo.setText(rad.get("slutdatum"));
                lblBeskrivningInfo.setText(rad.get("beskrivning"));
            } catch (Exception e) {
                System.out.println("Kunde inte hämta info: " + e.getMessage());
            }
        }

    }//GEN-LAST:event_cbProjektValActionPerformed

    private void btnTillbakaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTillbakaActionPerformed
      new MenyProjektChef(idDB, epost).setVisible(true);
      this.dispose();
    }//GEN-LAST:event_btnTillbakaActionPerformed

    private void btnSeKostnadsstatistikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeKostnadsstatistikActionPerformed
     new ProjektchefProjektStatistik(idDB, aid).setVisible(true);
  
        ProjektchefProjektStatistik statistikFonster = new ProjektchefProjektStatistik(idDB, aid);
    statistikFonster.setLocationRelativeTo(null);
    statistikFonster.setVisible(true);
    
    }//GEN-LAST:event_btnSeKostnadsstatistikActionPerformed

private void fyllProjektLista(String sqlFraga) {
    try {
        cbProjektVal.removeAllItems();
        var rader = idDB.fetchRows(sqlFraga);
        if (rader != null) {
            for (var rad : rader) {
                cbProjektVal.addItem(rad.get("projektnamn"));
            }
            if (cbProjektVal.getItemCount() > 0) {
                cbProjektVal.setSelectedIndex(0); // Väljer första projektet i den nya listan
            }
        }
    } catch (Exception e) {
        System.out.println("Fel: " + e.getMessage());
    }
}
    
    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFiltreraPaStatus;
    private javax.swing.JButton btnFiltreraProjekt;
    private javax.swing.JButton btnRedigeraProjektUppgifter;
    private javax.swing.JButton btnSeKostnadsstatistik;
    private javax.swing.JButton btnTillbaka;
    private javax.swing.JComboBox<String> cbProjektVal;
    private javax.swing.JComboBox<String> cbStatusFilter;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel lblBeskrivning;
    private javax.swing.JLabel lblBeskrivningInfo;
    private javax.swing.JLabel lblBudgetInfo;
    private javax.swing.JLabel lblBudgetRubrik;
    private javax.swing.JLabel lblFiltreraPåStatus;
    private javax.swing.JLabel lblProjektadministration;
    private javax.swing.JLabel lblSlutDatumInfo;
    private javax.swing.JLabel lblSlutdatum;
    private javax.swing.JLabel lblSokProjekt;
    private javax.swing.JLabel lblSokProjektFran;
    private javax.swing.JLabel lblSokProjektTill;
    private javax.swing.JLabel lblStartDatum;
    private javax.swing.JLabel lblStartDatumInfo;
    private javax.swing.JLabel lblStatusInfo;
    private javax.swing.JLabel lblStatusRubrik;
    private javax.swing.JPanel pnlLabel;
    private javax.swing.JPanel pnlMain;
    private javax.swing.JPanel pnlVanster;
    // End of variables declaration//GEN-END:variables
}
