/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *Klass för att visa statistik och listor över projekt
 *
 * @author elinjugas
 */
import oru.inf.InfDB;
import oru.inf.InfException;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;

public class ProjektchefProjektStatistik extends javax.swing.JFrame {

    private InfDB idDB;
    private int aid; //hämtar aid och epost för den inloggade
    private String inloggadEpost;

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ProjektchefProjektStatistik.class.getName());

    /**
     * Creates new form ProjektchefProjektStatistik
     */
    public ProjektchefProjektStatistik(InfDB idb, int aid, String epost) {
        initComponents();

        this.idDB = idb;
        this.aid = aid;
        this.inloggadEpost = epost;

        // Fyller statsistik ettiketerna och tabellen direkt vid start 
        laddaStatistikKort();
        laddaTabell();

    }

    //Häntar data från databasen  och att sedan visa den i korten
    //Använder SQL för att räjna antal, sumera kostnad och räkna ut snitt
    private void laddaStatistikKort() {
        try {
            //För att få fram ett värde
            String antal = idDB.fetchSingle("SELECT count(*) FROM projekt");
            String summa = idDB.fetchSingle("SELECT sum(kostnad) FROM projekt");
            String snitt = idDB.fetchSingle("SELECT avg(kostnad) FROM projekt");

            // Använder valideringsklassen för att snygga till siffror
            lblAntalVarde.setText(antal != null ? antal : "0");
            lblSummaVarde.setText(Valideringsklass2.formateraValuta(summa));
            lblSnittVarde.setText(Valideringsklass2.formateraValuta(snitt));

        } catch (InfException ex) {
            // Visar felmeddelnande om de görs en felhantering
            JOptionPane.showMessageDialog(this, "Kunde inte hämta statistik: " + ex.getMessage());
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
    }

    //Fuller tabellen med projektdata på det valda filtret
    //Rensar mtabellen och ritar upp den på nytt vid varja anrop
    private void laddaTabell() {

        try {
            //Kontrollera att ett filtigt val gjorts i comboboxen via validering
            Object valdStatusObjekt = cbStatusFilter.getSelectedItem();
            if (!Valideringsklass2.comboValt(valdStatusObjekt, "status")) {
                return;
            }

            String valdStatus = valdStatusObjekt.toString();
            String sql = "SELECT projektnamn, status, kostnad FROM projekt";
            //Söker om användaren valt en specifik status

            if (!valdStatus.equals("Alla")) {
                sql += " WHERE status = '" + valdStatus + "'";
            }

            ArrayList<HashMap<String, String>> rader = idDB.fetchRows(sql);
            //Hänmtar tabellens modell för att kunna skapa rader
            DefaultTableModel model = (DefaultTableModel) tblProjektLista.getModel();
            model.setRowCount(0); //Tömmer tabellen inför ett nytt anrop

            //Validering och kontroll om data hittades, annars får man ett felmeddelande
            if (Valideringsklass2.kontrolleraHittadData(rader, "Inga projekt matchar valt filter.")) {
                for (HashMap<String, String> rad : rader) {
                    //Skapar en array av objekt som representerar en rad
                    Object[] tabellRad = {
                        rad.get("projektnamn"),
                        rad.get("status"),
                        Valideringsklass2.formateraValuta(rad.get("kostnad"))
                    };
                    model.addRow(tabellRad); //Lägger till raden i tabellen
                }
            }
        } catch (InfException ex) {
            JOptionPane.showMessageDialog(this, "Ett tekniskt fel uppstod när tabellen skulle laddas.");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        pnlNorth = new javax.swing.JPanel();
        lblProjektStatistik = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        pnlAktivaProjekt = new javax.swing.JPanel();
        lblAntalVarde = new javax.swing.JLabel();
        pnlTotalInvestering = new javax.swing.JPanel();
        lblSummaVarde = new javax.swing.JLabel();
        pnlProjektbudget = new javax.swing.JPanel();
        lblSnittVarde = new javax.swing.JLabel();
        pnlFiltreraProjekt = new javax.swing.JPanel();
        cbStatusFilter = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblProjektLista = new javax.swing.JTable();
        btnTillbaka = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(51, 153, 255));
        setPreferredSize(new java.awt.Dimension(700, 500));

        pnlNorth.setBackground(new java.awt.Color(51, 153, 255));

        lblProjektStatistik.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblProjektStatistik.setForeground(new java.awt.Color(255, 255, 255));
        lblProjektStatistik.setText("Projektstatistik");
        lblProjektStatistik.setToolTipText("");

        javax.swing.GroupLayout pnlNorthLayout = new javax.swing.GroupLayout(pnlNorth);
        pnlNorth.setLayout(pnlNorthLayout);
        pnlNorthLayout.setHorizontalGroup(
            pnlNorthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNorthLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblProjektStatistik, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlNorthLayout.setVerticalGroup(
            pnlNorthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlNorthLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblProjektStatistik, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        pnlAktivaProjekt.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Antal aktiva projekt", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Helvetica Neue", 0, 14))); // NOI18N

        lblAntalVarde.setText("Antal:");

        javax.swing.GroupLayout pnlAktivaProjektLayout = new javax.swing.GroupLayout(pnlAktivaProjekt);
        pnlAktivaProjekt.setLayout(pnlAktivaProjektLayout);
        pnlAktivaProjektLayout.setHorizontalGroup(
            pnlAktivaProjektLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAktivaProjektLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(lblAntalVarde, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );
        pnlAktivaProjektLayout.setVerticalGroup(
            pnlAktivaProjektLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAktivaProjektLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(lblAntalVarde, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pnlTotalInvestering.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Total investering", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Helvetica Neue", 0, 14))); // NOI18N

        lblSummaVarde.setText("Summa:");

        javax.swing.GroupLayout pnlTotalInvesteringLayout = new javax.swing.GroupLayout(pnlTotalInvestering);
        pnlTotalInvestering.setLayout(pnlTotalInvesteringLayout);
        pnlTotalInvesteringLayout.setHorizontalGroup(
            pnlTotalInvesteringLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTotalInvesteringLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lblSummaVarde, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );
        pnlTotalInvesteringLayout.setVerticalGroup(
            pnlTotalInvesteringLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTotalInvesteringLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(lblSummaVarde)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlProjektbudget.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Genomsnittlig projektbudget", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Helvetica Neue", 0, 14))); // NOI18N

        lblSnittVarde.setText("Summa:");

        javax.swing.GroupLayout pnlProjektbudgetLayout = new javax.swing.GroupLayout(pnlProjektbudget);
        pnlProjektbudget.setLayout(pnlProjektbudgetLayout);
        pnlProjektbudgetLayout.setHorizontalGroup(
            pnlProjektbudgetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProjektbudgetLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblSnittVarde)
                .addContainerGap(166, Short.MAX_VALUE))
        );
        pnlProjektbudgetLayout.setVerticalGroup(
            pnlProjektbudgetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProjektbudgetLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(lblSnittVarde)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(pnlAktivaProjekt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlTotalInvestering, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlProjektbudget, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(pnlTotalInvestering, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlProjektbudget, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlAktivaProjekt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        cbStatusFilter.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Alla", "Pågående", "Planerat", "Pausade", "Avslutat", " " }));
        cbStatusFilter.addActionListener(this::cbStatusFilterActionPerformed);

        jLabel2.setText("Filtrera på status:");

        tblProjektLista.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Projektnamn", "Status", "Kostnad"
            }
        ));
        jScrollPane2.setViewportView(tblProjektLista);

        btnTillbaka.setText("Tillbaka");
        btnTillbaka.addActionListener(this::btnTillbakaActionPerformed);

        javax.swing.GroupLayout pnlFiltreraProjektLayout = new javax.swing.GroupLayout(pnlFiltreraProjekt);
        pnlFiltreraProjekt.setLayout(pnlFiltreraProjektLayout);
        pnlFiltreraProjektLayout.setHorizontalGroup(
            pnlFiltreraProjektLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFiltreraProjektLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbStatusFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTillbaka)
                .addContainerGap(13, Short.MAX_VALUE))
        );
        pnlFiltreraProjektLayout.setVerticalGroup(
            pnlFiltreraProjektLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFiltreraProjektLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(pnlFiltreraProjektLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbStatusFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnlFiltreraProjektLayout.createSequentialGroup()
                .addGroup(pnlFiltreraProjektLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnTillbaka)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlNorth, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(pnlFiltreraProjekt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlNorth, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlFiltreraProjekt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Händelsehanterare för när användaren byter filter i rullsitan
    //Gör en omladdning av tabellen med nya filteringen
    private void cbStatusFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbStatusFilterActionPerformed
        laddaTabell();
    }//GEN-LAST:event_cbStatusFilterActionPerformed

    //Ständer statistikvyn och återgår till huvudmeny för projektchefer. 
    private void btnTillbakaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTillbakaActionPerformed
        new MenyProjektChef(idDB, inloggadEpost).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnTillbakaActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTillbaka;
    private javax.swing.JComboBox<String> cbStatusFilter;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblAntalVarde;
    private javax.swing.JLabel lblProjektStatistik;
    private javax.swing.JLabel lblSnittVarde;
    private javax.swing.JLabel lblSummaVarde;
    private javax.swing.JPanel pnlAktivaProjekt;
    private javax.swing.JPanel pnlFiltreraProjekt;
    private javax.swing.JPanel pnlNorth;
    private javax.swing.JPanel pnlProjektbudget;
    private javax.swing.JPanel pnlTotalInvestering;
    private javax.swing.JTable tblProjektLista;
    // End of variables declaration//GEN-END:variables
}
