/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 * Klass för att redigera projektuppgifter
 * Validerar användarens inmatning och skickar UPDATE-fråga till databasen
 *
 * @author elinjugas
 */
import oru.inf.InfException;
import oru.inf.InfDB;
import java.util.HashMap;
import javax.swing.JOptionPane;

public class ProjektchefRedigeraProjekt extends javax.swing.JFrame {

    private InfDB idDB;
    private String projektnamn; //Lagrar namnet för att hitta rätt rad i databasen
    private String valtProjekt;
    private int aid;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ProjektchefRedigeraProjekt.class.getName());
private String epost;
    
    /**
     * Creates new form ProjektchefRedigeraProjekt
     */
    public ProjektchefRedigeraProjekt(InfDB idDB, String projektnamn, int aid, String epost) {

        this.idDB = idDB;
        this.projektnamn = projektnamn;
        this.aid = aid;
        this.epost = epost;

        initComponents();

        //Fyller i befintig data
        fyllProjektData();
        lblRedigeraProjekt.setText("REDIGERA: " + projektnamn.toUpperCase());

    }

    private void fyllProjektData() {
        try {
            //Hämtar rad baserat på projektnamnet

            String sql = "SELECT * FROM projekt WHERE projektnamn = '" + projektnamn + "'";
            HashMap<String, String> projektData = idDB.fetchRow(sql);

            if (projektData != null) {
                //Sätter texten i komponenterna baserat på databasens kolumnnamn
                txtNamn.setText(projektData.get("projektnamn"));
                txtBeskrivning.setText(projektData.get("beskrivning"));
                txtBudget.setText(projektData.get("kostnad"));
                txtStartdatum.setText(projektData.get("startdatum"));
                txtSlutdatum.setText(projektData.get("slutdatum"));
                txtStatus.setText(projektData.get("status"));

                lblRedigeraProjekt.setText("Redigera projekt: " + projektnamn);

            }
        } catch (InfException e) {
            JOptionPane.showMessageDialog(null, "Kunde inte hämta projektdata!");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlHeader = new javax.swing.JPanel();
        pnlMain = new javax.swing.JPanel();
        lblRedigeraProjekt = new javax.swing.JLabel();
        pnlMainInfo = new javax.swing.JPanel();
        lblStatus = new javax.swing.JLabel();
        txtStatus = new javax.swing.JTextField();
        lblBudget = new javax.swing.JLabel();
        lblStartdatum = new javax.swing.JLabel();
        lblSlutdatum = new javax.swing.JLabel();
        lblBeskrivning = new javax.swing.JLabel();
        txtBudget = new javax.swing.JTextField();
        txtStartdatum = new javax.swing.JTextField();
        txtSlutdatum = new javax.swing.JTextField();
        txtBeskrivning = new javax.swing.JTextField();
        btnAvbryt = new javax.swing.JButton();
        btnSparaÄndringar = new javax.swing.JButton();
        lblNamn = new javax.swing.JLabel();
        txtNamn = new javax.swing.JTextField();
        btnTillbaka = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlHeader.setBackground(new java.awt.Color(245, 245, 245));

        javax.swing.GroupLayout pnlHeaderLayout = new javax.swing.GroupLayout(pnlHeader);
        pnlHeader.setLayout(pnlHeaderLayout);
        pnlHeaderLayout.setHorizontalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 726, Short.MAX_VALUE)
        );
        pnlHeaderLayout.setVerticalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        getContentPane().add(pnlHeader, java.awt.BorderLayout.CENTER);

        pnlMain.setBackground(new java.awt.Color(51, 153, 255));

        lblRedigeraProjekt.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblRedigeraProjekt.setForeground(new java.awt.Color(255, 255, 255));
        lblRedigeraProjekt.setText("Redigera projektuppgifter: [Namn]");
        lblRedigeraProjekt.setToolTipText("");

        pnlMainInfo.setBorder(javax.swing.BorderFactory.createEmptyBorder(30, 30, 30, 30));

        lblStatus.setText("Status:");

        txtStatus.addActionListener(this::txtStatusActionPerformed);

        lblBudget.setText("Budget:");

        lblStartdatum.setText("Startdatum:");

        lblSlutdatum.setText("Slutdatum: ");

        lblBeskrivning.setText("Beskrivning:");

        btnAvbryt.setText("Avbryt");
        btnAvbryt.addActionListener(this::btnAvbrytActionPerformed);

        btnSparaÄndringar.setText("Spara Ändringar");
        btnSparaÄndringar.addActionListener(this::btnSparaÄndringarActionPerformed);

        lblNamn.setText("Namn:");

        btnTillbaka.setText("Tillbaka");
        btnTillbaka.addActionListener(this::btnTillbakaActionPerformed);

        javax.swing.GroupLayout pnlMainInfoLayout = new javax.swing.GroupLayout(pnlMainInfo);
        pnlMainInfo.setLayout(pnlMainInfoLayout);
        pnlMainInfoLayout.setHorizontalGroup(
            pnlMainInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMainInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlMainInfoLayout.createSequentialGroup()
                        .addComponent(lblBeskrivning)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                        .addComponent(txtBeskrivning, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlMainInfoLayout.createSequentialGroup()
                        .addComponent(lblSlutdatum)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtSlutdatum, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlMainInfoLayout.createSequentialGroup()
                        .addComponent(lblStartdatum)
                        .addGap(50, 50, 50)
                        .addComponent(txtStartdatum))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlMainInfoLayout.createSequentialGroup()
                        .addComponent(lblBudget)
                        .addGap(72, 72, 72)
                        .addComponent(txtBudget))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlMainInfoLayout.createSequentialGroup()
                        .addGroup(pnlMainInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblStatus)
                            .addComponent(lblNamn))
                        .addGap(76, 76, 76)
                        .addGroup(pnlMainInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtStatus)
                            .addComponent(txtNamn)))
                    .addGroup(pnlMainInfoLayout.createSequentialGroup()
                        .addComponent(btnTillbaka)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAvbryt)
                        .addGap(18, 18, 18)
                        .addComponent(btnSparaÄndringar)))
                .addContainerGap())
        );
        pnlMainInfoLayout.setVerticalGroup(
            pnlMainInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainInfoLayout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(pnlMainInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNamn)
                    .addComponent(txtNamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlMainInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblStatus, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtStatus, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlMainInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblBudget, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtBudget, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlMainInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblStartdatum, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtStartdatum, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlMainInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSlutdatum, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtSlutdatum, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlMainInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBeskrivning)
                    .addComponent(txtBeskrivning, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(pnlMainInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTillbaka)
                    .addComponent(btnAvbryt)
                    .addComponent(btnSparaÄndringar)))
        );

        javax.swing.GroupLayout pnlMainLayout = new javax.swing.GroupLayout(pnlMain);
        pnlMain.setLayout(pnlMainLayout);
        pnlMainLayout.setHorizontalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblRedigeraProjekt, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMainLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlMainInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76))
        );
        pnlMainLayout.setVerticalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblRedigeraProjekt)
                .addGap(18, 18, 18)
                .addComponent(pnlMainInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );

        getContentPane().add(pnlMain, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSparaÄndringarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSparaÄndringarActionPerformed
        // Validera alla fält steg för steg via valideringsklass2
        //Kontrollerar formatet på namn, budget, datum och status
        if (Valideringsklass2.faltHarVarde(txtNamn, "Namn")
                && Valideringsklass2.arGiltigDecimal(txtBudget, "Budget")
                && Valideringsklass2.arGiltigtDatum(txtStartdatum)
                && Valideringsklass2.arGiltigtDatum(txtSlutdatum)
                && Valideringsklass2.arGiltigStatus(txtStatus)) {

            // Kontorllerar att slutdatum inte ligger före startdatim
            if (!Valideringsklass2.arGiltigtDatumIntervall(txtStartdatum, txtSlutdatum)) {
                return; //Avbryt om datumen är ologiska 
            }

            // Hämtar de nya värdena från täxtfältet
            String nyttNamn = txtNamn.getText().trim();
            //Ersätter komma med punkt för att SQL ska förstå decimaltal
            String nyBudget = txtBudget.getText().trim().replace(',', '.');
            String nyBeskrivning = txtBeskrivning.getText().trim();
            String start = txtStartdatum.getText().trim();
            String slut = txtSlutdatum.getText().trim();
            String status = txtStatus.getText().trim();

            try {
                // Bygger update
    String sql = "UPDATE projekt SET "
            + "projektnamn = '" + nyttNamn + "', "
            + "beskrivning = '" + nyBeskrivning + "', "
            + "startdatum = '" + start + "', "
            + "slutdatum = '" + slut + "', "
            + "kostnad = " + nyBudget + ", "
            + "status = '" + status + "' "
            + "WHERE projektnamn = '" + this.projektnamn + "'";

    idDB.update(sql);
    
    //Visar meddelande
                JOptionPane.showMessageDialog(this, "Projektet har uppdaterats!");

                // Uppdatera lokalt namn om det ändrades ifall användaren fortsätter redigera
                this.projektnamn = nyttNamn;
                fyllProjektData();
                

            } catch (InfException e) {
                JOptionPane.showMessageDialog(this, "Ett tekniskt fel uppstod vid sparande.");
                logger.log(java.util.logging.Level.SEVERE, null, e);
            }
        }
    }//GEN-LAST:event_btnSparaÄndringarActionPerformed

    private void txtStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStatusActionPerformed

    }//GEN-LAST:event_txtStatusActionPerformed

    private void btnAvbrytActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAvbrytActionPerformed
        //Informerar om att ändringar inte sparats 
        JOptionPane.showMessageDialog(this, "Ändringarna har avbrutits och fälten har återställts.");
        fyllProjektData(); //Återställer textfälten för hur de va innan
    }//GEN-LAST:event_btnAvbrytActionPerformed

    //Går tillbaka till administrationsdönstret
    private void btnTillbakaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTillbakaActionPerformed
        new ProjektchefProjektAdministration(idDB, aid, this.epost).setVisible(true);
        this.dispose();

    }//GEN-LAST:event_btnTillbakaActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAvbryt;
    private javax.swing.JButton btnSparaÄndringar;
    private javax.swing.JButton btnTillbaka;
    private javax.swing.JLabel lblBeskrivning;
    private javax.swing.JLabel lblBudget;
    private javax.swing.JLabel lblNamn;
    private javax.swing.JLabel lblRedigeraProjekt;
    private javax.swing.JLabel lblSlutdatum;
    private javax.swing.JLabel lblStartdatum;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JPanel pnlHeader;
    private javax.swing.JPanel pnlMain;
    private javax.swing.JPanel pnlMainInfo;
    private javax.swing.JTextField txtBeskrivning;
    private javax.swing.JTextField txtBudget;
    private javax.swing.JTextField txtNamn;
    private javax.swing.JTextField txtSlutdatum;
    private javax.swing.JTextField txtStartdatum;
    private javax.swing.JTextField txtStatus;
    // End of variables declaration//GEN-END:variables
}
