/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import oru.inf.InfDB;
import oru.inf.InfException;
/**
 *
 * @author User
 */
public class projektForHandlaggare extends javax.swing.JFrame {
    private InfDB idb;
    private String inloggadAnvandare;
    

    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(projektForHandlaggare.class.getName());

    /**
     * Creates new form projektForHandlaggare
     */
    public projektForHandlaggare(InfDB idb, String inloggadAnvandare) {
        this.idb = idb;
        this.inloggadAnvandare = inloggadAnvandare;
        initComponents();
        hamtaTilldeladeProjekt();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        //java.awt.EventQueue.invokeLater(() -> new projektForHandlaggare().setVisible(true));
    }
public void hamtaTilldeladeProjekt(){
    try{ String fraga = "SELECT projekt.projektnamn, projekt.status, projekt.startdatum " 
            + "FROM projekt " + "Join ans_proj ON projekt.pid = ans_proj.pid " + 
            "JOIN anstalld on ans_proj.aid = anstalld.aid " + 
            "Where anstalld.epost = '" + inloggadAnvandare + "';"; 
    java.util.ArrayList<java.util.HashMap<String, String>>projektLista = idb.fetchRows(fraga);
    if(projektLista !=null && !projektLista.isEmpty()){
        System.out.println("Dina tilldelade projekt: ");
        for(java.util.HashMap<String, String>rad : projektLista){
            String projektNamn = rad.get("projektnamn");
            String projektStatus = rad.get("status"); 
            System.out.println("Projekt: " + projektNamn);
            System.out.println("Status: " + projektStatus);
        }
    }
        else { System.out.println("Du har inga tilldelade projekt just nu. ");
    }
    }
    catch(InfException ex){
            System.out.println("SystemFel " + ex.getLocalizedMessage());
            }
        
                    
        }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
